---
- block:

  - name: instala pacotes necessários
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - munin-node

  - name: libera acesso pelo munin-master
    lineinfile:
      path: /etc/munin/munin-node.conf
      regexp: "^allow "
      line: "allow {{ munin_master_allow }}"
    when: munin_master_allow|d
    notify: reinicia munin-node

  tags: munin-node