---
- block:

  - name: configura timeout
    lineinfile:
      path: "/etc/default/grub"
      regexp: "^GRUB_TIMEOUT="
      line: "GRUB_TIMEOUT={{ grub_config_timeout }}"
    when: grub_config_timeout|d
    notify: reconfigura grub

  - name: configura command line
    lineinfile:
      path: "/etc/default/grub"
      regexp: "^GRUB_CMDLINE_LINUX="
      line: "GRUB_CMDLINE_LINUX=\"{{ grub_config_cmdline }}\""
    when: grub_config_cmdline|d
    notify: reconfigura grub

  tags: ["grub:conf"]
