---
- name: instala pacotes necessários
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - supervisor
  tags: ["supervisor"]

- name: carrega supervisor
  service:
    name: supervisor
    state: started
    enabled: yes
  tags: ["supervisor"]
