---
- name: instala pacotes necessários
  apt:
    name:
      - supervisor
    state: present
    install_recommends: no
  tags: ["supervisor"]

- name: carrega supervisor
  service:
    name: supervisor
    state: started
    enabled: yes
  tags: ["supervisor"]
