---
- block:
    - name: instala pacotes necessários
      apt:
        name:
          - ca-certificates

    - name: cria diretório de destino
      file:
        state: directory
        path: "/opt/winbox"

    - name: download do winbox
      get_url:
        url: "https://download.mikrotik.com/winbox/{{ winbox_version }}/winbox.exe"
        dest: "/opt/winbox/winbox-{{ winbox_version }}.exe"

    - name: cria link
      file:
        state: link
        src: "/opt/winbox/winbox-{{ winbox_version }}.exe"
        dest: "/opt/winbox/winbox.exe"

    - name: copia script para facilitar carregamento
      copy:
        src: "winbox"
        dest: "/usr/local/bin/winbox"
        mode: 0755

  tags: ["winbox"]
