---
- block:
    - name: cria diretório de destino
      file:
        state: directory
        path: "/opt/winbox"

    - name: faz download do winbox
      include_role:
        name: zanardo/download
      vars:
        url: "https://download.mikrotik.com/winbox/{{ winbox_version }}/winbox.exe"
        file: "winbox-{{ winbox_version }}.exe"
        dir: "/opt/winbox"
        mode: 0o755
        owner: "root"
        group: "root"

    - name: cria link
      file:
        state: link
        src: "/opt/winbox/winbox-{{ winbox_version }}.exe"
        dest: "/opt/winbox/winbox.exe"

    - name: copia script para facilitar carregamento
      copy:
        src: "winbox"
        dest: "/usr/local/bin/winbox"
        mode: 0755

  tags: ["winbox"]
