---
- name: instala pacotes necessários
  apt:
    name:
      - build-essential

- name: faz download do onefetch
  include_role:
    name: zanardo/download
  vars:
    url: https://github.com/o2sh/onefetch/archive/v{{ onefetch_version }}.tar.gz
    file: onefetch-{{ onefetch_version }}.tar.gz
    dir: /tmp

- name: descompacta e compila o pacote
  become: yes
  become_user: _builder
  shell: |
    warn=no
    executable=/bin/bash
    cd ~ && \
    rm -rf onefetch* && \
    tar xf /tmp/onefetch-{{ onefetch_version }}.tar.gz && \
    cd onefetch-{{ onefetch_version }} && \
    source /etc/profile.d/rust.sh && \
    cargo build --release && \
    cp -f target/release/onefetch /tmp && \
    cd ~ && \
    rm -rf onefetch*

- name: instala o binário
  copy:
    remote_src: yes
    src: /tmp/onefetch
    dest: /usr/local/bin/onefetch
    owner: root
    group: root
    mode: 0o755

- name: remove arquivos temporários
  file:
    state: absent
    path: /tmp/{{ item }}
  loop:
    - onefetch-{{ onefetch_version }}.tar.gz
    - onefetch
