---
- name: instala onefetch
  include_role:
    name: zanardo/rust-app
    apply:
      tags: ["onefetch"]
  vars:
    rust_app_name: onefetch
    rust_app_version: "{{ onefetch_version }}"
    rust_app_apt_packages:
      - build-essential
    rust_app_cmd_get_version: >
      /usr/local/bin/onefetch --version | cut -f2 -d' '
    rust_app_url: >
      https://github.com/o2sh/onefetch/archive/v{{ onefetch_version }}.tar.gz
    rust_app_executables:
      - onefetch
  tags: ["onefetch"]
