---
- name: instala pacotes necessários
  apt:
    name:
      - build-essential
      - pkg-config
      - libssl-dev

- name: faz download do cargo-edit
  include_role:
    name: zanardo/download
  vars:
    url: https://github.com/killercup/cargo-edit/archive/v{{ cargo_edit_version }}.tar.gz
    file: cargo-edit-{{ cargo_edit_version }}.tar.gz
    dir: /tmp

- name: descompacta e compila o pacote
  become: yes
  become_user: _builder
  shell: |
    warn=no
    executable=/bin/bash
    cd ~ && \
    rm -rf cargo-edit* && \
    tar xf /tmp/cargo-edit-{{ cargo_edit_version }}.tar.gz && \
    cd cargo-edit-{{ cargo_edit_version }} && \
    source /etc/profile.d/rust.sh && \
    cargo build --release && \
    cp -f target/release/cargo-add /tmp && \
    cp -f target/release/cargo-rm /tmp && \
    cp -f target/release/cargo-upgrade /tmp && \
    cd ~ && \
    rm -rf cargo-edit*

- name: instala os binários
  copy:
    remote_src: yes
    src: /tmp/{{ item }}
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: 0o755
  loop:
    - cargo-add
    - cargo-rm
    - cargo-upgrade

- name: remove arquivos temporários
  file:
    state: absent
    path: /tmp/{{ item }}
  loop:
    - cargo-edit-{{ cargo_edit_version }}.tar.gz
    - cargo-add
    - cargo-rm
    - cargo-upgrade
