---
- name: instala cargo-edit
  include_role:
    name: zanardo/rust-app
    apply:
      tags: ["cargo-edit"]
  vars:
    rust_app_name: cargo-edit
    rust_app_version: "{{ cargo_edit_version }}"
    rust_app_apt_packages:
      - build-essential
      - pkg-config
      - libssl-dev
    rust_app_cmd_get_version: >
      /usr/local/bin/cargo-add --version | cut -f2 -d' '
    rust_app_url: >
      https://github.com/killercup/cargo-edit/archive/v{{ cargo_edit_version }}.tar.gz
    rust_app_executables:
      - cargo-add
      - cargo-rm
      - cargo-upgrade

  tags: ["cargo-edit"]
