---
- name: instala pacotes necessários
  apt:
    state: present
    name: "{{ item }}"
    install_recommends: no
  with_items:
    - build-essential
    - libx11-6
    - libxext6
    - libjpeg62-turbo
    - libpng12-0
    - cmake
    - zlib1g-dev
    - libx11-dev 
    - libjpeg62-turbo-dev
    - gettext
    - libxext-dev
    - libpng12-dev
    - ca-certificates
    - procps

- name: download do fltk para cache local
  connection: local
  get_url:
    url: "http://fltk.org/pub/fltk/{{ tigervnc_fltk_version }}/fltk-{{ tigervnc_fltk_version }}-source.tar.gz"
    dest: "~/.cache/ansible/fltk-{{ tigervnc_fltk_version }}.tar.gz"
    sha256sum: "{{ tigervnc_fltk_sha256 }}"

- name: download do tigervnc para cache local
  connection: local
  get_url:
    url: "https://github.com/TigerVNC/tigervnc/archive/v{{ tigervnc_version }}.tar.gz"
    dest: "~/.cache/ansible/tigervnc-{{ tigervnc_version }}.tar.gz"

- name: upload fltk
  copy:
    src: "~/.cache/ansible/fltk-{{ tigervnc_fltk_version }}.tar.gz"
    dest: "/tmp/fltk-{{ tigervnc_fltk_version }}.tar.gz"
    owner: nobody
    group: nogroup

- name: upload tigervnc
  copy:
    src: "~/.cache/ansible/tigervnc-{{ tigervnc_version }}.tar.gz"
    dest: "/tmp/tigervnc-{{ tigervnc_version }}.tar.gz"
    owner: nobody
    group: nogroup

- name: cria diretório de destino
  file:
    state: directory
    path: /opt/tigervnc
    recurse: yes
    owner: nobody
    group: nogroup

- name: compila e instala fltk
  become: yes
  become_user: nobody
  shell: >
    warn=no
    chdir=/tmp
    tar xvvf "fltk-{{ tigervnc_fltk_version }}.tar.gz" &&
    cd "fltk-{{ tigervnc_fltk_version }}" &&
    ./configure --prefix=/opt/tigervnc &&
    make -j2 &&
    make install

- name: compila e instala tigervnc
  become: yes
  become_user: nobody
  shell: >
    warn=no
    chdir=/tmp
    tar xvvf "tigervnc-{{ tigervnc_version }}.tar.gz" &&
    cd "tigervnc-{{ tigervnc_version }}" &&
    cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX:STRING="/opt/tigervnc" -DFLTK_FLUID_EXECUTABLE:STRING="/opt/tigervnc/bin/fluid" &&
    sed -i -e 's/$/ -ldl -lpng/' vncviewer/CMakeFiles/vncviewer.dir/link.txt &&
    make -j2 &&
    make install

- name: corrige permissões
  file:
    state: directory
    recurse: yes
    path: /opt/tigervnc
    owner: root
    group: root

- name: remove diretórios e arquivos temporários
  become: yes
  become_user: nobody
  file:
    state: absent
    path: "/tmp/{{ item }}"
  with_items:
    - "fltk-{{ tigervnc_fltk_version }}.tar.gz"
    - "fltk-{{ tigervnc_fltk_version }}"
    - "tigervnc-{{ tigervnc_version }}.tar.gz"
    - "tigervnc-{{ tigervnc_version }}"
