---
- name: instala pacotes necessários
  apt: state=present name={{ item }}
  with_items:
    - supervisor
    - build-essential
    - python
    - python-dev
    - python3
    - python3-dev
    - ca-certificates
    - libpcre3-dev

- name: cria diretórios
  file: state=directory path={{ item }}
  with_items:
    - /opt/uwsgi
    - /opt/uwsgi/vassals
    - /opt/uwsgi/plugins

- name: define permissões
  shell: >
    warn=no
    chown -R nobody:nogroup /opt/uwsgi

- name: download do tarball
  get_url: >
    url="https://github.com/unbit/uwsgi/archive/{{ uwsgi_version }}.tar.gz"
    dest="/tmp/uwsgi-{{ uwsgi_version }}.tar.gz"

- name: extrai o tarball
  shell: >
    warn=no
    chdir="/tmp"
    mkdir -p "uwsgi-{{ uwsgi_version }}" &&
    tar -C "uwsgi-{{ uwsgi_version }}" --strip-components=1 \
      -xzf "/tmp/uwsgi-{{ uwsgi_version }}.tar.gz" &&
    chown -R nobody:nogroup "uwsgi-{{ uwsgi_version }}/"

- name: compila core
  become: yes
  become_user: nobody
  shell: >
    chdir="/tmp/uwsgi-{{ uwsgi_version }}"
    UWSGI_PROFILE_OVERRIDE="plugin_dir=/opt/uwsgi/plugins" \
    make PROFILE={{ uwsgi_profile }}

- name: compila plugins de versões do python
  become: yes
  become_user: nobody
  shell: >
    chdir="/tmp/uwsgi-{{ uwsgi_version }}"
    PYTHON=python{{ item }} ./uwsgi --build-plugin "plugins/python python{{ item|replace('.','') }}"
  with_items: "{{ uwsgi_plugins_python }}"

- name: compila plugins
  become: yes
  become_user: nobody
  shell: >
    chdir="/tmp/uwsgi-{{ uwsgi_version }}"
    ./uwsgi --build-plugin "plugins/{{ item }}"
  with_items: "{{ uwsgi_plugins }}"

- name: remove plugins de compilação anterior
  shell: 
    warn=no
    rm -f /opt/uwsgi/plugins/*.so
  failed_when: False

- name: instala core
  become: yes
  become_user: nobody
  shell: >
    chdir="/tmp/uwsgi-{{ uwsgi_version }}"
    install -m 0755 uwsgi /opt/uwsgi/uwsgi

- name: instala plugins
  become: yes
  become_user: nobody
  shell: >
    chdir="/tmp/uwsgi-{{ uwsgi_version }}"
    cp *.so /opt/uwsgi/plugins/
  failed_when: False

- name: remove arquivos temporários
  file: >
    state=absent
    path="/tmp/uwsgi-{{ uwsgi_version }}"

- name: cria link para uwsgi em /usr/local/bin
  file: >
    state=link
    path=/usr/local/bin/uwsgi
    src=/opt/uwsgi/uwsgi

- name: copia arquivo de configuração default do emperor
  template: >
    src=uwsgi.ini.j2
    dest=/opt/uwsgi/uwsgi.ini
  when: uwsgi_emperor_ini is not defined
  notify: reinicia uwsgi

- name: copia serviço do supervisor
  copy: >
    src=uwsgi.supervisor
    dest=/opt/uwsgi/uwsgi.supervisor
  notify: reinicia uwsgi

- name: cria link do serviço do supervisor
  file: >
    state=link
    path=/etc/supervisor/conf.d/uwsgi.conf
    src=/opt/uwsgi/uwsgi.supervisor
  notify: reinicia uwsgi
