---
- name: checa versão instalada
  shell: /opt/uwsgi/uwsgi --version
  register: uwsgi_register_version
  changed_when: False
  failed_when: False

- name: download, compilação, instalação
  include: install.yml
  when: uwsgi_register_version.stdout != uwsgi_version or uwsgi_force_install

- name: copia arquivo de configuração customizado do emperor
  template: >
    src={{ uwsgi_emperor_ini }}
    dest=/opt/uwsgi/uwsgi.ini
  when: uwsgi_emperor_ini is defined
  notify: reinicia uwsgi
