---
- block:
    - name: instala pacotes necessários
      apt:
        name:
          - sanoid
        state: present

    - name: cria diretório de configurações
      file:
        state: directory
        path: "/etc/sanoid"

    - name: copia arquivo de configuração
      copy:
        src: "{{ sanoid_conf }}"
        dest: "/etc/sanoid/sanoid.conf"
      when: sanoid_conf is defined
      tags: ["sanoid:conf"]

  tags: ["sanoid"]
