---
- set_fact:
    python_version: "{{ outer_item }}"
    python_maj_min: "{{ '.'.join(outer_item.split('.')[0:2]) }}"

- name: checa versão instalada
  shell: >
    "/opt/python{{ python_maj_min }}/bin/python{{ python_maj_min }} -V 2>&1 | cut -d' ' -f2"
  register: python_register_version
  changed_when: False
  failed_when: False

- include: install.yml
  when: python_register_version.stdout != python_version or python_force_install is defined

- name: instala pip
  shell: >
    creates="/opt/python{{ python_maj_min }}/bin/pip{{ python_maj_min }}"
    /opt/python{{ python_maj_min }}/bin/python{{ python_maj_min }} -m ensurepip

- name: instala virtualenv
  shell: >
    warn=no
    creates="/opt/python{{ python_maj_min }}/bin/virtualenv"
    /opt/python{{ python_maj_min }}/bin/pip{{ python_maj_min }} install virtualenv
