---
- name: instala pacotes necessários
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - python3
    - python-dev
    - python3-dev
    - python-pip
    - python3-pip
  tags: ["python"]

- name: instala virtualenv atualizado /usr/local
  shell:
    warn=no
    creates=/usr/local/bin/virtualenv
    pip3 install --upgrade virtualenv
  tags: ["python"]
