---
- name: instala pacotes
  apt:
    name: shorewall
    state: present
  tags: ["shorewall"]

- name: habilita início no boot
  lineinfile:
    dest: /etc/default/shorewall
    line: "startup=1"
    regexp: "^startup="
    state: present
  notify: reconfigura shorewall
  tags: ["shorewall"]

- name: verifica se a reconfiguração falhou
  file:
    path: /tmp/ansible-shorewall-restart
    state: absent
  notify: reconfigura shorewall
  tags: ["shorewall", "shorewall:conf"]

- name: copia arquivos de configuração
  template:
    src: "{{ shorewall_conf_local_path }}/{{ item }}"
    dest: /etc/shorewall/
    owner: root
    mode: 0600
  with_items: "{{ shorewall_conf_files }}"
  notify: reconfigura shorewall
  tags: ["shorewall", "shorewall:conf"]
