---
- block:

  - name: instala pacotes necessários
    apt:
      name:
        - ca-certificates
      state: present

  - name: download do executável para cache local
    connection: local
    get_url:
      url: "https://github.com/borgbackup/borg/releases/download/{{ borg_version }}/borg-linux64"
      dest: "~/.cache/ansible/borg-{{ borg_version }}"

  - name: download da assinatura para cache local
    connection: local
    get_url:
      url: "https://github.com/borgbackup/borg/releases/download/{{ borg_version }}/borg-linux64.asc"
      dest: "~/.cache/ansible/borg-{{ borg_version }}.asc"

  - name: upload dos arquivos para o destino
    copy:
      src: "~/.cache/ansible/{{ item }}"
      dest: "/tmp/{{ item }}"
    with_items:
      - "borg-{{ borg_version }}"
      - "borg-{{ borg_version }}.asc"

  - name: upload da chave pública para verificação
    copy:
      src: "thomas.pub"
      dest: "/tmp/thomas.pub"

  - name: importa chave do gpg no keyring
    shell: >
      chdir=/tmp
      gpg --no-default-keyring --homedir=. --import thomas.pub

  - name: verifica assinatura gpg
    shell: >
      chdir=/tmp
      gpg --homedir=. --verify "borg-{{ borg_version}}.asc" "borg-{{ borg_version }}"

  - name: instala executável para /usr/local/bin
    copy:
      remote_src: yes
      src: "/tmp/borg-{{ borg_version }}"
      dest: "/usr/local/bin/borg"
      mode: 0755
      owner: root
      group: root

  - name: remove arquivos temporários
    file:
      state: absent
      path: "/tmp/{{ item }}"
    with_items:
      - "borg-{{ borg_version }}"
      - "borg-{{ borg_version }}.asc"
      - "thomas.pub"

  tags: borg
