---
- name: instala isort
  include_role:
    name: zanardo/python-app
    apply:
      tags: ["isort"]
  vars:
    python_app_name: isort
    python_app_version: "{{ isort_version }}"
    python_app_scripts:
      - isort
  tags: ["isort"]
