---
- name: instala pacotes necessários
  apt:
    name:
      - nginx-light
    state: present
  tags: ["nginx"]

- name: copia arquivo de configuração
  template:
    src: "{{ nginx_conf }}"
    dest: /etc/nginx/nginx.conf
  when: nginx_conf|d()
  notify: reinicia nginx
  tags: ["nginx", "nginx:conf"]
