---
- block:
    - name: instala pacotes necessários
      apt:
        name:
          - nginx-light

    - name: copia arquivo de configuração
      template:
        src: "{{ nginx_conf }}"
        dest: /etc/nginx/nginx.conf
      when: nginx_conf|d()
      notify: reinicia nginx
      tags: ["nginx:conf"]

  tags: ["nginx"]
