---
- name: instala flake8
  include_role:
    name: zanardo/python-app
    apply:
      tags: ["flake8"]
  vars:
    python_app_name: flake8
    python_app_version: "{{ flake8_version }}"
    python_app_scripts:
      - flake8
  tags: ["flake8"]
