---
- name: reinicia postgresql
  service:
    name: postgresql
    state: restarted

- name: aguarda postgresql iniciar
  wait_for:
    timeout: 5
    path: "/run/postgresql/9.4-main.pid"
    state: present
