---
- name: instala ripgrep
  include_role:
    name: zanardo/rust-app
  vars:
    rust_app_name: ripgrep
    rust_app_version: "{{ ripgrep_version }}"
    rust_app_apt_packages:
      - build-essential
    rust_app_cmd_get_version: >
      /usr/local/bin/rg --version | head -1 | cut -f2 -d' '
    rust_app_url: >
      https://github.com/BurntSushi/ripgrep/archive/{{ ripgrep_version }}.tar.gz
    rust_app_executables:
      - rg
  tags: ["ripgrep"]
