#!/bin/bash

set -exuo pipefail

VERSION="${1}"
test -n "${VERSION}"
test -n "${ARTIFACTS}"

rm -f "/tmp/dbeaver-ce_${VERSION}_amd64.deb.tmp"

if [ ! -f "/tmp/dbeaver-ce_${VERSION}_amd64.deb" ]; then
    wget -O "/tmp/dbeaver-ce_${VERSION}_amd64.deb.tmp" \
        "https://github.com/dbeaver/dbeaver/releases/download/${VERSION}/dbeaver-ce_${VERSION}_amd64.deb"
    mv -f "/tmp/dbeaver-ce_${VERSION}_amd64.deb.tmp" \
        "/tmp/dbeaver-ce_${VERSION}_amd64.deb"
fi

rsync -vax --ignore-existing \
    "/tmp/dbeaver-ce_${VERSION}_amd64.deb" \
    "${ARTIFACTS}/dbeaver/"
