---
- name: instala pacotes necessários
  apt:
    name:
      - build-essential

- name: faz download do watchexec
  include_role:
    name: zanardo/download
  vars:
    url: https://github.com/watchexec/watchexec/archive/{{ watchexec_version }}.tar.gz
    file: watchexec-{{ watchexec_version }}.tar.gz
    dir: /tmp

- name: descompacta e compila o pacote
  become: yes
  become_user: _builder
  shell: |
    warn=no
    executable=/bin/bash
    cd ~ && \
    rm -rf watchexec* && \
    tar xf /tmp/watchexec-{{ watchexec_version }}.tar.gz && \
    cd watchexec-{{ watchexec_version }} && \
    source /etc/profile.d/rust.sh && \
    cargo build --release && \
    cp -f target/release/watchexec /tmp && \
    cd ~ && \
    rm -rf watchexec*

- name: instala o binário
  copy:
    remote_src: yes
    src: /tmp/watchexec
    dest: /usr/local/bin/watchexec
    owner: root
    group: root
    mode: 0o755

- name: remove arquivos temporários
  file:
    state: absent
    path: /tmp/{{ item }}
  loop:
    - watchexec-{{ watchexec_version }}.tar.gz
    - watchexec
