- name: instala watchexec
  include_role:
    name: zanardo/rust-app
    apply:
      tags: ["watchexec"]
  vars:
    rust_app_name: watchexec
    rust_app_version: "{{ watchexec_version }}"
    rust_app_apt_packages:
      - build-essential
    rust_app_cmd_get_version: >
      /usr/local/bin/watchexec --version | cut -f2 -d' '
    rust_app_url: >
      https://github.com/watchexec/watchexec/archive/{{ watchexec_version }}.tar.gz
    rust_app_executables:
      - watchexec
  tags: ["watchexec"]
