---
- block:

  - name: instala pacotes necessários
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
        - python3-docker
      state: present

  - name: instala pacotes necessários - debian buster
    apt:
      name:
        - python-docker
    when: ansible_distribution_release in ["buster"]

  - name: adiciona chave gpg no apt para docker
    apt_key:
      state: present
      url: "{{ docker_apt_repo }}/linux/debian/gpg"

  # FIXME: Usamos "buster" pois o repositório do bullseye ainda não está liberado!

  - name: adiciona repositório do docker
    apt_repository:
      repo: "deb [arch=amd64] {{ docker_apt_repo }}/linux/debian buster stable"
      state: present
      filename: docker

  - name: instala docker
    apt:
      state: present
      name: docker-ce
      install_recommends: no
