---
- block:

  - name: instala pacotes necessários
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
      state: present

  - name: adiciona chave gpg no apt para docker
    apt_key:
      state: present
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      keyserver: pgp.mit.edu

  - name: adiciona repositório do docker
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
      state: present
      filename: docker

  - name: cria diretório de configurações
    file:
      state: directory
      path: /etc/docker

  # Ver https://github.com/moby/moby/issues/22339.

  - name: configura endpoints da API - cria diretório de override
    file:
      path: /etc/systemd/system/docker.service.d/
      state: directory
    when: 'docker_daemon_config["hosts"]|d()'
    notify: reinicia docker

  - name: configura endpoints da API - cria override
    copy:
      dest: /etc/systemd/system/docker.service.d/override_hosts.conf
      content: |
        [Service]
        ExecStart=
        ExecStart=/usr/bin/dockerd
    when: 'docker_daemon_config["hosts"]|d()'
    notify: reinicia docker

  - name: remove override de endpoints da API
    file:
      state: absent
      path: /etc/systemd/system/docker.service.d/override_hosts.conf
    when: 'not docker_daemon_config["hosts"]|d()'
    notify: reinicia docker

  - name: configura docker
    copy:
      content: "{{ docker_daemon_config | to_json }}"
      dest: /etc/docker/daemon.json
    notify: reinicia docker

  - name: instala docker
    apt:
      state: present
      name: docker-ce
      install_recommends: no

  tags: docker
