---
- block:

  - name: instala pacotes necessários
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
        - python-docker
      state: present

  - name: adiciona chave gpg no apt para docker
    apt_key:
      state: present
      url: "https://download.docker.com/linux/debian/gpg"

  - name: adiciona repositório do docker
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
      state: present
      filename: docker

  - name: cria diretório de configurações
    file:
      state: directory
      path: /etc/docker

  # Ver https://github.com/moby/moby/issues/22339.

  - name: configura endpoints da API - cria diretório de override
    file:
      path: /etc/systemd/system/docker.service.d/
      state: directory
    when: 'docker_daemon_config["hosts"]|d()'
    notify: reinicia docker

  - name: configura endpoints da API - cria override
    copy:
      dest: /etc/systemd/system/docker.service.d/override_hosts.conf
      content: |
        [Service]
        ExecStart=
        ExecStart=/usr/bin/dockerd
    when: 'docker_daemon_config["hosts"]|d()'
    notify: reinicia docker

  - name: remove override de endpoints da API
    file:
      state: absent
      path: /etc/systemd/system/docker.service.d/override_hosts.conf
    when: 'not docker_daemon_config["hosts"]|d()'
    notify: reinicia docker

  - name: configura docker
    copy:
      content: "{{ docker_daemon_config | to_json }}"
      dest: /etc/docker/daemon.json
    notify: reinicia docker

  - name: instala docker
    apt:
      state: present
      name: docker-ce
      install_recommends: no

  - name: copia script para agendar gc nas imagens sem tags
    copy:
      src: "docker-gc-images.sh"
      dest: "/usr/local/bin/docker-gc-images.sh"
      owner: "root"
      group: "root"
      mode: "0755"

  - name: agenda script de gc nas imagens sem tags
    cron:
      name: "remove imagens do docker sem tags"
      special_time: "daily"
      job: "/usr/local/bin/docker-gc-images.sh 2>&1 | /usr/bin/logger"

  - name: cria diretório para logs dos containers
    file:
      state: directory
      path: "/var/log/dockers"

  - name: copia configurações para rotacionamento dos logs
    copy:
      src: dockers.logrotate
      dest: "/etc/logrotate.d/dockers"

  - name: copia configurações para salvamento dos logs via syslog
    copy:
      src: dockers.rsyslog
      dest: "/etc/rsyslog.d/30-dockers.conf"
    notify: reinicia rsyslog

  tags: docker
