---
- block:

  - name: cria diretório de configurações
    file:
      state: directory
      path: /etc/docker

  - name: configura docker
    copy:
      content: "{{ docker_daemon_config | to_json }}"
      dest: /etc/docker/daemon.json
    notify: reinicia docker

  - include_tasks: "install-{{ ansible_distribution|lower }}.yml"

  - name: adiciona usuários para grupo docker
    user:
      name: "{{ item }}"
      groups: "docker"
      append: yes
    loop: "{{ docker_users }}"

  tags: ["docker"]
