---
- name: instala pacotes necessários
  apt:
    name:
      - build-essential

- name: faz download do fd
  include_role:
    name: zanardo/download
  vars:
    url: https://github.com/sharkdp/fd/archive/v{{ fd_version }}.tar.gz
    file: fd-{{ fd_version }}.tar.gz
    dir: /tmp

- name: descompacta e compila o pacote
  become: yes
  become_user: _builder
  shell: |
    warn=no
    executable=/bin/bash
    cd ~ && \
    rm -rf fd* && \
    tar xf /tmp/fd-{{ fd_version }}.tar.gz && \
    cd fd-{{ fd_version }} && \
    source /etc/profile.d/rust.sh && \
    cargo build --release && \
    cp -f target/release/fd /tmp && \
    cd ~ && \
    rm -rf fd*

- name: instala o binário
  copy:
    remote_src: yes
    src: /tmp/fd
    dest: /usr/local/bin/fd
    owner: root
    group: root
    mode: 0o755

- name: remove arquivos temporários
  file:
    state: absent
    path: /tmp/{{ item }}
  loop:
    - fd-{{ fd_version }}.tar.gz
    - fd
