---
- block:

  - name: checa versão instalada
    shell:
      warn=no
      /usr/local/bin/fd --version | cut -f2 -d' '
    register: fd_register_version
    changed_when: False
    check_mode: no
    failed_when: False

  - name: instala fd
    include_tasks: install.yml
    when: fd_register_version.stdout != fd_version or fd_force_install is defined

  tags: ["fd"]
