---
- name: instala fd
  include_role:
    name: zanardo/rust-app
    apply:
      tags: ["fd"]
  vars:
    rust_app_name: fd
    rust_app_version: "{{ fd_version }}"
    rust_app_apt_packages:
      - build-essential
    rust_app_cmd_get_version: >
      /usr/local/bin/fd --version | cut -f2 -d' '
    rust_app_url: >
      https://github.com/sharkdp/fd/archive/v{{ fd_version }}.tar.gz
    rust_app_executables:
      - fd
  tags: ["fd"]
