---
- name: checa versão instalada
  shell: >
    warn=no
    grep "__VERSION__ = " /opt/rrd/rrd
  register: rrd_register_version
  changed_when: False
  failed_when: False
  tags: ["rrd"]

- include: install.yml
  when: rrd_register_version.stdout != "__VERSION__ = '0.3'" or rrd_force_install is defined
  tags: ["rrd"]
