---
- block:

  - name: checa versão instalada
    shell:
      warn=no
      /usr/local/bin/syncthing --version | cut -f2 -d' '
    register: syncthing_register_version
    changed_when: False
    check_mode: no
    failed_when: False

  - name: instala syncthing
    include_tasks: install.yml
    when: syncthing_register_version.stdout != "v"+ syncthing_version or syncthing_force_install is defined

  tags: ["syncthing"]
