---
- block:
  - name: instala pacotes necessários
    apt:
      name:
        - ca-certificates
      state: present
    tags: prometheus-node-exporter

  - name: download do tarball para cache local
    connection: local
    run_once: yes
    get_url:
      url: "https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_exporter_version }}/{{ item }}"
      dest: "~/.cache/ansible/{{ item }}"
    with_items:
      - "node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ prometheus_node_exporter_arch }}.tar.gz"

  - name: obtém versão instalada do prometheus node exporter
    shell:
      /usr/local/bin/node_exporter --version 2>&1 | \
        sed -ne 's/^node_exporter, version \([^ ]*\) .*$/\1/p'
    changed_when: False
    failed_when: false
    check_mode: no
    register: version

  - name: upload do tarball para o destino
    copy:
      src: "~/.cache/ansible/{{ item }}"
      dest: "/tmp/{{ item }}"
    with_items:
      - "node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ prometheus_node_exporter_arch }}.tar.gz"
    when: version.stdout != prometheus_node_exporter_version

  - name: cria usuário para execução
    user:
      name: prometheus
      state: present
      shell: /bin/bash
      system: yes
      createhome: no

  - name: descompacta tarball
    shell:
      warn=no
      chdir=/usr/local/bin
      tar --strip-components=1 -xf "/tmp/{{ item }}" "{{ item|replace(".tar.gz", "") }}/node_exporter" && \
      chown root:root node_exporter
    with_items:
      - "node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ prometheus_node_exporter_arch }}.tar.gz"
    when: version.stdout != prometheus_node_exporter_version

  - name: copia unit do systemd
    template:
      src: prometheus-node-exporter.service
      dest: /etc/systemd/system/prometheus-node-exporter.service
    notify: reinicia prometheus-node-exporter
    tags: prometheus-node-exporter:conf

  - name: ativa serviço no systemd
    systemd:
      name: prometheus-node-exporter
      enabled: yes
      state: started
    notify: reinicia prometheus-node-exporter

  - name: remove arquivos temporários
    file:
      path: "/tmp/{{ item }}"
      state: absent
    with_items:
      - "node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ prometheus_node_exporter_arch }}.tar.gz"

  tags: prometheus-node-exporter
