---
- block:

  - name: instala pacotes necessários
    apt:
      name:
        - ca-certificates
      state: present

  - name: download do tarball para cache local
    connection: local
    run_once: yes
    get_url:
      url: "https://s3-us-west-2.amazonaws.com/grafana-releases/release/{{ item }}"
      dest: "~/.cache/ansible/{{ item }}"
    with_items:
      - "grafana-{{ grafana_version }}.linux-{{ grafana_arch }}.tar.gz"

  - name: obtém versão instalada do grafana
    shell:
      /opt/grafana/bin/grafana-server -v 2>&1 | \
        sed -ne 's/^Version \([^ $]*\).*$/\1/p'
    changed_when: False
    failed_when: false
    check_mode: no
    register: version

  - name: remove versão anterior instalada
    file:
      path: /opt/grafana
      state: absent
    when: version.stdout != grafana_version

  - name: upload do tarball para o destino
    copy:
      src: "~/.cache/ansible/{{ item }}"
      dest: "/tmp/{{ item }}"
    with_items:
      - "grafana-{{ grafana_version }}.linux-{{ grafana_arch }}.tar.gz"
    when: version.stdout != grafana_version

  - name: cria usuário para execução
    user:
      name: grafana
      state: present
      shell: /bin/bash
      system: yes
      createhome: no

  - name: cria diretório de instalação
    file:
      path: /opt/grafana
      state: directory

  - name: cria diretório de dados
    file:
      path: "{{ grafana_data_path }}"
      state: directory
      mode: 0700
      owner: grafana
      group: grafana

  - name: descompacta tarball
    shell:
      warn=no
      chdir=/opt/grafana
      tar --strip-components=1 -xf "/tmp/{{ item }}" && \
      chown -R root:root /opt/grafana/
    with_items:
      - "grafana-{{ grafana_version }}.linux-{{ grafana_arch }}.tar.gz"
    when: version.stdout != grafana_version

  - name: copia unit do systemd
    template:
      src: grafana.service
      dest: /etc/systemd/system/grafana.service
    notify: reinicia grafana

  - name: copia arquivo de configuração
    template:
      src: "{{ grafana_conf }}"
      dest: /opt/grafana/conf/grafana.ini
      owner: grafana
      group: grafana
      mode: 0600
    notify: reinicia grafana
    tags: grafana:conf

  - name: ativa serviço no systemd
    systemd:
      name: grafana
      enabled: yes
    notify: reinicia grafana

  - name: remove arquivos temporários
    file:
      path: "/tmp/{{ item }}"
      state: absent
    with_items:
      - "grafana-{{ grafana_version }}.linux-{{ grafana_arch }}.tar.gz"

  tags: grafana
