---
- block:

  - name: instala pacotes necessários
    apt:
      name: "{{ item }}"
    with_items:
      - uwsgi

  - name: copia arquivos de configurações
    template:
      src: "{{ item }}"
      dest: "/etc/uwsgi/apps-enabled/{{ item|basename }}"
    with_items: "{{ uwsgi_conf_files }}"
    when: uwsgi_conf_files|d([])
    notify: reinicia uwsgi

  tags: uwsgi
