---
- name: instala black
  include_role:
    name: zanardo/python-app
    apply:
      tags: ["black"]
  vars:
    python_app_name: black
    python_app_version: "{{ black_version }}"
    python_app_scripts:
      - black
      - blackd
      - black-primer
  tags: ["black"]
