---
- name: cria diretórios de configuração
  file:
    state: directory
    recurse: yes
    path: /etc/opt/pgbouncer
    owner: root
    group: opt-pgbouncer
    mode: 0750

- name: copia unit do supervisor
  copy:
    src: pgbouncer.supervisor
    dest: /etc/supervisor/conf.d/pgbouncer.conf
  notify: reinicia pgbouncer

- name: copia arquivo de configuração
  template:
    src: "{{ pgbouncer_conf }}"
    dest: /etc/opt/pgbouncer/pgbouncer.ini
    owner: root
    group: opt-pgbouncer
    mode: 0640
  notify: reconfigura pgbouncer

- name: copia arquivo de autenticação
  template:
    src: "{{ pgbouncer_userlist_conf }}"
    dest: /etc/opt/pgbouncer/userlist.txt
    owner: root
    group: opt-pgbouncer
    mode: 0640
  notify: reconfigura pgbouncer
