---
- name: instala pacotes necessários
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - make
    - gcc
    - libc6-dev
    - libevent-dev
    - libevent-2.0-5
    - libssl-dev
    - libssl1.0.0
    - ca-certificates
    - supervisor

- name: cria usuário pgbouncer
  user:
    name: pgbouncer
    system: yes
    shell: /bin/bash

- name: faz o download do tarball
  connection: local
  get_url:
    url: "https://pgbouncer.github.io/downloads/files/{{ pgbouncer_version }}/pgbouncer-{{ pgbouncer_version }}.tar.gz"
    dest: "~/.cache/ansible/pgbouncer-{{ pgbouncer_version }}.tar.gz"

- name: faz upload do tarball
  copy:
    src: "~/.cache/ansible/pgbouncer-{{ pgbouncer_version }}.tar.gz"
    dest: "/tmp/pgbouncer-{{ pgbouncer_version }}.tar.gz"

- name: descompacta o tarball
  unarchive:
    copy: no
    dest: /tmp
    owner: pgbouncer
    group: pgbouncer
    src: "/tmp/pgbouncer-{{ pgbouncer_version }}.tar.gz"

- name: compila
  become: true
  become_user: pgbouncer
  shell: >
    chdir="/tmp/pgbouncer-{{ pgbouncer_version }}"
    ./configure && make

- name: instala
  shell: >
    chdir="/tmp/pgbouncer-{{ pgbouncer_version }}"
    install -o root -g root -m 0755 pgbouncer /usr/local/bin/pgbouncer

- name: remove arquivos temporários
  file:
    state: absent
    path: "/tmp/{{ item }}"
  with_items:
    - "pgbouncer-{{ pgbouncer_version }}.tar.gz"
    - "pgbouncer-{{ pgbouncer_version }}"
