---
- name: verifica versão instalada
  shell: >
    warn=no
    /opt/pgbouncer/bin/pgbouncer --version | cut -d" " -f3
  changed_when: False
  failed_when: False
  register: pgbouncer_register_version
  tags: ["pgbouncer"]

- include: install.yml
  when: pgbouncer_register_version.stdout != pgbouncer_version or pgbouncer_force_install is defined
  tags: ["pgbouncer"]

- include: config.yml
  tags: ["pgbouncer", "pgbouncer:conf"]
