---
- block:

  - block:

    - name: verifica se proxy apt está ativo
      wait_for:
        host: "{{ apt_proxy_host }}"
        port: "{{ apt_proxy_port }}"
        timeout: 5
      when: apt_proxy_host|d
      register: apt_proxy_active

    rescue:

    - name: proxy inativo
      debug:
        msg: "apt_proxy_host:apt_proxy_port não alcançável"

  - name: ativa proxy para apt
    copy:
      dest: /etc/apt/apt.conf.d/01proxy
      content: "Acquire::http::Proxy \"http://{{ apt_proxy_host }}:{{ apt_proxy_port }}/\";\n"
      owner: root
      group: root
      mode: 0644
    when: apt_proxy_host|d and apt_proxy_active|succeeded
    register: apt_proxy_set

  - name: desativa proxy para apt
    copy:
      dest: /etc/apt/apt.conf.d/01proxy
      content: ""
      owner: root
      group: root
      mode: 0644
    when: apt_proxy_set|skipped

  - name: desativa proxy para repositórios https para apt
    copy:
      dest: /etc/apt/apt.conf.d/01proxy_nohttps
      content: "Acquire::https::Proxy \"false\";"
      owner: root
      group: root
      mode: 0644
    when: apt_proxy_no_https is defined

  - name: configura apt sources.list
    copy:
      src: "sources.{{ ansible_distribution_release }}"
      dest: /etc/apt/sources.list
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution_release in ('jessie')
    notify: atualiza apt

  - name: desativa dns para ssh
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      line: "UseDNS no"
      regexp: "^UseDNS .*$"
    notify: reinicia ssh

  - meta: flush_handlers

  - name: reduz tempo de espera no menu do grub
    lineinfile:
      dest: /etc/default/grub
      line: "GRUB_TIMEOUT=1"
      regexp: "^#?GRUB_TIMEOUT="
      state: present
    notify: reconfigura grub

  - name: instala pacotes básicos
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-dater-host

  tags: common
