---
- name: faz download do firejail
  include_role:
    name: zanardo/download
  vars:
    url: https://github.com/netblue30/firejail/archive/{{ firejail_version }}.tar.gz
    file: firejail-{{ firejail_version }}.tar.gz
    dir: /tmp

- name: descompacta e compila o pacote
  become: yes
  become_user: _builder
  shell: |
    warn=no
    cd ~ && \
    rm -rf firejail* && \
    tar xf /tmp/firejail-{{ firejail_version }}.tar.gz && \
    cd firejail-{{ firejail_version }} && \
    ./configure && \
    make -j$(nproc)

- name: instala o firejail
  shell: |
    warn=no
    make -C /var/opt/_builder/firejail-{{ firejail_version }} install-strip && \
    rm -rf "/var/opt/_builder/firejail-{{ firejail_version }}"

- name: remove arquivos temporários
  file:
    state: absent
    path: /tmp/{{ item }}
  loop:
    - firejail-{{ firejail_version }}.tar.gz
