---
- block:

  - name: instala pacotes necessários
    apt:
      name:
        - nfs-common
        - nfs-kernel-server
      state: present

  - name: define porta fixa para rpc.mountd
    lineinfile:
      dest: /etc/default/nfs-kernel-server
      line: 'RPCMOUNTDOPTS="--manage-gids --port 32767 --no-nfs-version 4'
      regexp: "^RPCMOUNTDOPTS="
      state: present
    notify: reinicia nfs-kernel-server

  - name: define porta fixa para statd
    lineinfile:
      dest: /etc/default/nfs-common
      line: 'STATDOPTS="--port 32765 --outgoing-port 32766"'
      regexp: "^STATDOPTS="
      state: present
    notify: reinicia nfs-common

  - name: copia arquivo de exports
    template:
      src: exports.j2
      dest: /etc/exports
      owner: root
      group: root
      mode: 0644
    notify: reinicia nfs-kernel-server

  - name: cria diretórios definidos em nfs_exports
    file:
      state: directory
      path: "{{ item.strip().split()[0] }}"
    with_items: "{{ nfs_exports }}"
    notify: reinicia nfs-kernel-server

  tags: ["nfs"]
