---
- block:

  - name: copia arquivo de configurações para /etc/network/interfaces
    template:
      src: "{{ interfaces_path }}"
      dest: /etc/network/interfaces
    when: interfaces_path|d

  - name: atualiza configurações em /etc/network/interfaces
    template:
      src: interfaces.j2
      dest: /etc/network/interfaces
    when: interfaces|d

  tags: interfaces
