---
- block:
    - name: instala pacotes necessários
      apt:
        name: util-linux

    - name: prepara serviço e timer para fstrim
      file:
        state: link
        src: /usr/share/doc/util-linux/examples/fstrim.{{ item }}
        dest: /etc/systemd/system/fstrim.{{ item }}
      loop:
        - service
        - timer
      when: ansible_distribution_release == "stretch"

    - name: habilita timer para fstrim
      systemd:
        name: fstrim.timer
        enabled: yes
        daemon_reload: yes

  tags: fstrim
