---
- block:

  - name: instala pacotes necessários
    apt:
      name:
        - ca-certificates
        - curl
        - build-essential

  - name: cria diretório de instalação
    file:
      state: directory
      path: /opt/rust
      owner: nobody
      group: nogroup

  - name: instala rust
    become: yes
    become_user: nobody
    shell:
      warn=no
      creates=/opt/rust/bin/cargo
      curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain none

  - name: obtém toolchains instalados
    changed_when: False
    become: yes
    become_user: nobody
    shell: |
      /opt/rust/bin/rustup toolchain list | \
        grep -v "no installed toolchains" | \
        sed 's/-x86_64-unknown-linux-gnu.*$//'
    register: toolchains

  - name: remove toolchains
    become: yes
    become_user: nobody
    shell: |
      /opt/rust/bin/rustup toolchain uninstall "{{ item }}"
    loop: "{{ toolchains.stdout_lines|d([]) | difference(rust_toolchains) }}"

  - name: instala toolchains
    become: yes
    become_user: nobody
    shell: |
      /opt/rust/bin/rustup toolchain install "{{ item }}"
    loop: "{{ rust_toolchains | difference(toolchains.stdout_lines|d([])) }}"

  - name: obtém o toolchain default
    become: yes
    become_user: nobody
    changed_when: False
    shell: |
      /opt/rust/bin/rustup default | \
        grep default | \
        sed 's/-x86_64-unknown-linux-gnu.*$//'
    register: default
    when: rust_toolchains|length > 0

  - name: define o toolchain default
    become: yes
    become_user: nobody
    shell: |
      /opt/rust/bin/rustup default {{ rust_toolchains[0] }}
    when:
      - rust_toolchains|length > 0
      - default.stdout|d("") != rust_toolchains[0]

  - name: obtém componentes instalados
    changed_when: False
    become: yes
    become_user: nobody
    shell: |
      /opt/rust/bin/rustup component list --installed | \
        sed 's/-x86_64-unknown-linux-gnu$//'
    register: components
    when: rust_toolchains|d([])

  - name: instala componentes do rust
    become: yes
    become_user: nobody
    shell: |
      /opt/rust/bin/rustup component add "{{ item }}"
    loop: "{{ rust_components|d([]) }}"
    when:
      - item not in components.stdout_lines|d([])
      - rust_toolchains|d([])

  - name: define variáveis de ambiente
    copy:
      content: |
        export PATH="/opt/rust/bin:$PATH"
        export RUSTUP_HOME="/opt/rust"
      dest: /etc/profile.d/rust.sh

  environment:
    RUSTUP_HOME: /opt/rust
    CARGO_HOME: /opt/rust
  tags: ["rust"]
