---
- block:

  - include_tasks: "packages-{{ ansible_distribution|lower }}.yml"

  - name: prepara instalação
    include_tasks: "python.yml"
    loop: "{{ python_src_versions|d([]) }}"
    loop_control:
      loop_var: python_version

  tags: ["python", "python-src"]
