---
- name: instala pacotes necessários
  apt:
    name:
      - build-essential
      - stow
      - libreadline-dev
      - libncursesw5-dev
      - zlib1g-dev
      - libbz2-dev
      - libexpat1-dev
      - libsqlite3-dev
      - libffi-dev
      - libdb-dev
      - libgdbm-dev
      - blt-dev
      - ca-certificates
      - libsqlite3-0
      - file
      - libexpat1
      - libmagic1
      - mime-support
      - libssl-dev
      - libssl1.1

- name: instala pacotes necessários - debian buster
  apt:
    name:
      - libffi6
  when: ansible_distribution_release in ("stretch", "buster")

- name: instala pacotes necessários - debian bullseys
  apt:
    name:
      - libffi7
  when: ansible_distribution_release in ("bullseye")
