---
- name: instala tox
  include_role:
    name: zanardo/python-app
    apply:
      tags: ["tox"]
  vars:
    python_app_name: tox
    python_app_version: "{{ tox_version }}"
    python_app_scripts:
      - tox
      - tox-quickstart
  tags: ["tox"]
