---
- block:
    - name: instala pacotes
      package:
        name: dnsmasq
        state: present

    - name: copia arquivo de configurações
      template:
        src: "{{ dnsmasq_conf }}"
        dest: /etc/dnsmasq.conf
        owner: root
        group: root
        mode: 0644
      when: dnsmasq_conf|d(False)
      notify: reinicia dnsmasq
      tags: "dnsmasq:conf"

    - name: habilita serviço
      systemd:
        name: dnsmasq
        enabled: yes
        state: started

  tags: "dnsmasq"
