---
- block:

    - name: cria usuário para rodar os coletores
      user:
        name: rrd-collectors
        system: yes
        state: present

    - name: checa se coletores estão instalados
      stat:
        path: "/opt/rrd-collectors-{{ rrd_collectors_version }}"
      register: rrd_collectors_installed

    - include: install.yml
      when: not rrd_collectors_installed.stat.exists or rrd_collectors_force_install is defined

    - name: agenda rrd-cpu no cron
      cron:
        name: "coletor rrd-cpu"
        user: "rrd-collectors"
        job: "exec /opt/rrd-collectors-{{ rrd_collectors_version }}/rrd-cpu {{ rrd_collectors_host }}:{{ rrd_collectors_port }} {{ ansible_hostname }}-cpu 1>/dev/null 2>/dev/null"

    - name: agenda rrd-mem no cron
      cron:
        name: "coletor rrd-mem"
        user: "rrd-collectors"
        job: "exec /opt/rrd-collectors-{{ rrd_collectors_version }}/rrd-mem {{ rrd_collectors_host }}:{{ rrd_collectors_port }} {{ ansible_hostname }}-mem 1>/dev/null 2>/dev/null"

    - name: agenda rrd-loadavg no cron
      cron:
        name: "coletor rrd-loadavg"
        user: "rrd-collectors"
        job: "exec /opt/rrd-collectors-{{ rrd_collectors_version }}/rrd-loadavg {{ rrd_collectors_host }}:{{ rrd_collectors_port }} {{ ansible_hostname }}-loadavg 1>/dev/null 2>/dev/null"

    - name: agenda rrd-nproc no cron
      cron:
        name: "coletor rrd-nproc"
        user: "rrd-collectors"
        job: "exec /opt/rrd-collectors-{{ rrd_collectors_version }}/rrd-nproc {{ rrd_collectors_host }}:{{ rrd_collectors_port }} {{ ansible_hostname }}-nproc 1>/dev/null 2>/dev/null"

    - name: agenda rrd-df no cron
      cron:
        name: "coletor rrd-df - {{ item.name }}"
        user: "rrd-collectors"
        job: "exec /opt/rrd-collectors-{{ rrd_collectors_version }}/rrd-df {{ rrd_collectors_host }}:{{ rrd_collectors_port }} {{ ansible_hostname }}-df-{{ item.name }} '{{ item.mount }}' 1>/dev/null 2>/dev/null"
      with_items: "{{ rrd_collectors_df_mounts }}"

    - name: agenda rrd-iftraff no cron
      cron:
        name: "coletor rrd-iftraff - {{ item }}"
        user: "rrd-collectors"
        job: "exec /opt/rrd-collectors-{{ rrd_collectors_version }}/rrd-iftraff {{ rrd_collectors_host }}:{{ rrd_collectors_port }} {{ ansible_hostname }}-iftraff-{{ item }} '{{ item }}' 1>/dev/null 2>/dev/null"
      with_items: "{{ rrd_collectors_iftraff_interfaces }}"

  tags: rrd-collectors
