---
- name: instala docker-compose
  include_role:
    name: zanardo/python-app
    apply:
      tags: ["docker-compose"]
  vars:
    python_app_name: docker-compose
    python_app_version: "{{ docker_compose_version }}"
    python_app_scripts:
      - docker-compose
  tags: ["docker-compose"]
