---
- name: configura o ssh no container
  lineinfile:
    path: "/var/lib/machines/{{ systemd_container_name }}/etc/ssh/sshd_config"
    regexp: "^#?PermitRootLogin.*$"
    line: "PermitRootLogin yes"
    state: present
  delegate_to: "{{ systemd_container_host }}"

- name: cria o diretório de configurações do ssh
  file:
    state: directory
    path: "/var/lib/machines/{{ systemd_container_name }}/root/.ssh"
  delegate_to: "{{ systemd_container_host }}"

- name: libera a chave de ssh
  copy:
    content: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    dest: "/var/lib/machines/{{ systemd_container_name }}/root/.ssh/authorized_keys"
  delegate_to: "{{ systemd_container_host }}"

- name: configura a interface de rede
  copy:
    content: |
      auto {{ systemd_container_interface }}
      iface host0 inet static
        address {{ systemd_container_ip }}/24
        gateway {{ systemd_container_gateway }}
    dest: "/var/lib/machines/{{ systemd_container_name }}/etc/network/interfaces"
  delegate_to: "{{ systemd_container_host }}"

- name: configura o dns do container
  copy:
    content: "{{ systemd_container_resolv }}"
    dest: "/var/lib/machines/{{ systemd_container_name }}/etc/resolv.conf"
  delegate_to: "{{ systemd_container_host }}"

- name: configura o nome do container
  copy:
    content: "{{ systemd_container_name }}"
    dest: "/var/lib/machines/{{ systemd_container_name }}/etc/hostname"
  delegate_to: "{{ systemd_container_host }}"

- name: configura hosts do container
  lineinfile:
    path: "/var/lib/machines/{{ systemd_container_name }}/etc/hosts"
    regexp: "^127.0.0.1 {{ systemd_container_name }}$"
    line: "127.0.0.1 {{ systemd_container_name }}"
    state: present
  delegate_to: "{{ systemd_container_host }}"

- name: configura timezone do container
  copy:
    content: "America/Sao_Paulo"
    dest: "/var/lib/machines/{{ systemd_container_name }}/etc/timezone"
  delegate_to: "{{ systemd_container_host }}"

- name: configura timezone do container
  command: systemd-nspawn -D /var/lib/machines/{{ systemd_container_name }} /usr/sbin/dpkg-reconfigure -f noninteractive tzdata
  delegate_to: "{{ systemd_container_host }}"

- name: configura locales do container
  copy:
    content: |
      pt_BR.UTF-8 UTF-8
      en_US.UTF-8 UTF-8
    dest: "/var/lib/machines/{{ systemd_container_name }}/etc/locale.gen"
  delegate_to: "{{ systemd_container_host }}"

- name: configura locale default do container
  copy:
    content: |
      LANG="en_US.UTF-8"
      LANGUAGE="en_US:en"
    dest: "/var/lib/machines/{{ systemd_container_name }}/etc/default/locale"
  delegate_to: "{{ systemd_container_host }}"

- name: gera locales do container
  command: systemd-nspawn -D /var/lib/machines/{{ systemd_container_name }} /usr/sbin/locale-gen
  delegate_to: "{{ systemd_container_host }}"

- name: configura inicialização de container - ativo
  command:
    warn=no
    machinectl enable {{ systemd_container_name }}
  delegate_to: "{{ systemd_container_host }}"
  changed_when: False
  when: systemd_container_autostart

- name: configura inicialização de container - desativado
  command:
    warn=no
    machinectl disable {{ systemd_container_name }}
  delegate_to: "{{ systemd_container_host }}"
  changed_when: False
  when: not systemd_container_autostart

- name: inicia container
  command:
    warn=no
    machinectl start {{ systemd_container_name }}
  changed_when: False
  delegate_to: "{{ systemd_container_host }}"

- name: aguarda ssh em {{ virt_install_ip }}
  connection: local
  wait_for:
    host: '{{ systemd_container_ip }}'
    port: 22
    state: present
    timeout: 60

- name: remove chaves de ssh em know_hosts local
  connection: local
  known_hosts:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ systemd_container_ip }}"
    - "{{ systemd_container_name }}"

- setup: {}
