---
- setup:
  delegate_to: "{{ systemd_container_host }}"

- name: executa tasks de criação do container
  include_tasks:
    create.yml
  when:
    - destroy_container is not defined

- setup: {}
  when:
    - destroy_container is not defined

- name: executa tasks de destruição do container
  include_tasks:
    destroy.yml
  when:
    - destroy_container is defined
    - destroy_container == systemd_container_name

- block:

  - name: finaliza playbook - container destruido
    debug: msg="container destruído - finalizando playbook"

  - name: esta task irá falhar para finalizar a execução do ansible
    failed_when: True
    debug:
      msg: "finalizando"
    delegate_to: "{{ systemd_container_host }}"

  when:
    - destroy_container is defined
    - destroy_container == systemd_container_name
