---
- setup:
  delegate_to: "{{ systemd_container_host }}"

- name: verifica se container existe
  stat:
    path: "{{ systemd_container_dir }}/.stage2.ok"
  register: checa_container_ja_existe
  delegate_to: "{{ systemd_container_host }}"

- block:

  - name: executa tasks de criação do container
    include_tasks: create.yml

  - setup: {}

  when:
    - destroy_container is not defined
    - checa_container_ja_existe.stat is defined
    - not checa_container_ja_existe.stat.exists

- block:

  - name: executa tasks de destruição do container
    include_tasks: destroy.yml
    when:
      - destroy_container is defined
      - destroy_container == systemd_container_name

  - name: finaliza playbook - container destruido
    debug: msg="container destruído - finalizando playbook"

  - name: esta task irá falhar para finalizar a execução do ansible
    failed_when: True
    debug:
      msg: "finalizando"
    delegate_to: "{{ systemd_container_host }}"

  when:
    - destroy_container is defined
    - destroy_container == systemd_container_name
