---
- setup:
  delegate_to: "{{ systemd_container_host }}"

- name: instala pacotes necessários - debian
  apt:
    state: present
    name:
      - debootstrap
      - systemd-container
    install_recommends: no
  delegate_to: "{{ systemd_container_host }}"

- name: cria diretório de configurações dos containers
  file:
    state: directory
    path: /etc/systemd/nspawn
  delegate_to: "{{ systemd_container_host }}"

- name: cria configurações do container
  copy:
    content: "{{ systemd_container_nspawn_config }}"
    dest: "/etc/systemd/nspawn/{{ systemd_container_name }}.nspawn"
  delegate_to: "{{ systemd_container_host }}"

- name: cria volume lógico no lvm do container
  lvol:
    size: "{{ systemd_container_lvm_size }}"
    vg: "{{ systemd_container_lvm_vg }}"
    lv: "{{ systemd_container_name }}"
  delegate_to: "{{ systemd_container_host }}"

- name: cria filesystem no volume lógico
  filesystem:
    dev: "/dev/{{ systemd_container_lvm_vg }}/{{ systemd_container_name }}"
    fstype: "{{ systemd_container_lvm_fs }}"
  delegate_to: "{{ systemd_container_host }}"

- name: cria diretório de montagem para o container
  file:
    state: directory
    path: "/var/lib/machines/{{ systemd_container_name }}"
  delegate_to: "{{ systemd_container_host }}"

- name: monta o filesystem do container
  mount:
    fstype: "{{ systemd_container_lvm_fs }}"
    path: "/var/lib/machines/{{ systemd_container_name }}"
    src: "/dev/{{ systemd_container_lvm_vg }}/{{ systemd_container_name }}"
    state: mounted
  delegate_to: "{{ systemd_container_host }}"

- name: cria container via debootstrap
  environment:
    http_proxy: "{{ systemd_container_http_proxy }}"
  command:
    creates="/var/lib/machines/{{ systemd_container_name }}/lib"
    debootstrap \
      --include=systemd,dbus,locales,python,sudo,openssh-server \
      "{{ systemd_container_debian }}" \
      "/var/lib/machines/{{ systemd_container_name }}" \
      "{{ systemd_container_debian_mirror }}"
  delegate_to: "{{ systemd_container_host }}"
  register: container_created

- name: bootstrap inicial do container
  include_tasks:
    create.yml
  when: container_created is changed

- setup: {}
