---
- block:

  - name: instala pacotes necessários
    apt:
      state: present
      name:
        - git

  - name: cria usuário para gitea
    user:
      name: git
      state: present
      shell: /bin/bash
      home: /srv/git

  - name: download do binário do gitea
    get_url:
      url: "https://github.com/go-gitea/gitea/releases/download/v{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64"
      dest: "/srv/git/gitea_{{ gitea_version }}"
      mode: 0755
      owner: root
      group: root

  - name: cria link para versão
    file:
      state: link
      dest: "/srv/git/gitea"
      src: "/srv/git/gitea_{{ gitea_version }}"
    notify: reinicia gitea

  - name: copia unit do supervisor
    template:
      src: gitea.supervisor
      dest: /etc/supervisor/conf.d/gitea.conf
    notify: reinicia gitea

  - name: cria diretório de configuração
    become: yes
    become_user: git
    file:
      state: directory
      recurse: yes
      path: /srv/git/custom/conf
    when: gitea_conf is defined

  - name: copia arquivo de configuração
    become: yes
    become_user: git
    template:
      src: "{{ gitea_conf }}"
      dest: /srv/git/custom/conf/app.ini
    when: gitea_conf is defined
    notify: reinicia gitea

  tags: gitea
