---
- block:

  - name: install needed packages
    apt:
      state: present
      name:
        - git

  - name: create user for gitea
    user:
      name: git
      state: present
      shell: /bin/bash
      home: /srv/git

  - name: download gitea binary in local machine
    connection: local
    get_url:
      url: "https://github.com/go-gitea/gitea/releases/download/v{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64"
      dest: "~/.cache/ansible/gitea-{{ gitea_version }}-linux-amd64"

  - name: upload gitea binary
    copy:
      src: "~/.cache/ansible/gitea-{{ gitea_version }}-linux-amd64"
      dest: /srv/git/gitea
      mode: 0755
      owner: root
      group: root
    notify: restart gitea

  - name: copy supervisor unit
    template:
      src: gitea.supervisor
      dest: /etc/supervisor/conf.d/gitea.conf
    notify: restart gitea

  - name: create custom configuration directory
    become: yes
    become_user: git
    file:
      state: directory
      recurse: yes
      path: /srv/git/custom/conf
    when: gitea_conf is defined

  - name: copy custom configuration
    become: yes
    become_user: git
    template:
      src: "{{ gitea_conf }}"
      dest: /srv/git/custom/conf/app.ini
    when: gitea_conf is defined
    notify: restart gitea

  tags: gitea
