---
- block:

  - name: cria diretórios para os pacotes
    file:
      state: directory
      path: /opt/pynvim
      owner: nobody
      group: nogroup

  - name: instala os pacotes
    become: yes
    become_user: nobody
    pip:
      name: pynvim
      version: "{{ pynvim_version|d(omit) }}"
      virtualenv_python: /usr/bin/python3
      virtualenv: /opt/pynvim

  tags: ["pynvim"]
