---
- name: instala pynvim
  include_role:
    name: zanardo/python-app
    apply:
      tags: ["pynvim"]
  vars:
    python_app_name: pynvim
    python_app_version: "{{ pynvim_version }}"
    python_app_scripts: []
  tags: ["pynvim"]
