---
- block:

  - name: instala pacotes necessários
    apt:
      name: "{{ item }}"
    with_items:
      - git
      - cgit
      - python3-markdown
      - python3-pygments

  - name: copia arquivo de configuração
    template:
      src: "{{ cgit_conf }}"
      dest: /etc/cgitrc
    when: cgit_conf|d('')
    tags:
      - cgit:conf

  tags:
    - cgit
