---
- meta: flush_handlers

- name: remove arquivo /reboot-me
  file:
    path: /reboot-me
    state: absent
  register: reboot_register

- name: reinicia máquina
  shell: ( sleep 3 && reboot & )
  when: reboot_register is changed

- name: aguarda porta tcp {{ virt_waitfor_port }} em {{ virt_install_ip }}
  connection: local
  wait_for:
    host: '{{ virt_install_ip }}'
    port: '{{ virt_waitfor_port }}'
    state: present
    timeout: 300
    delay: 15
  when: reboot_register is changed
