---
- name: faz download da distribuição do firefox - versão específica
  include_role:
    name: zanardo/download
  vars:
    url: https://ftp.mozilla.org/pub/firefox/releases/{{ firefox_version }}/linux-x86_64/{{ firefox_lang }}/firefox-{{ firefox_version }}.tar.bz2
    file: firefox-{{ firefox_lang }}-{{ firefox_version }}.tar.bz2
    dir: /tmp
  when: firefox_version != "latest"

- name: faz download da distribuição do firefox - última versão
  include_role:
    name: zanardo/download
  vars:
    url: https://download.mozilla.org/?product=firefox-latest&os=linux64&lang={{ firefox_lang }}
    file: firefox-{{ firefox_lang }}-{{ firefox_version }}.tar.bz2
    dir: /tmp
  when: firefox_version == "latest"

- name: remove instalação atual do firefox
  file:
    state: absent
    path: "{{ firefox_path }}"

- name: cria diretório de instalação
  file:
    state: directory
    path: "{{ firefox_path }}"
    mode: "0755"

- name: descompacta pacote do firefox
  unarchive:
    remote_src: yes
    src: "/tmp/firefox-{{ firefox_lang }}-{{ firefox_version }}.tar.bz2"
    dest: "{{ firefox_path }}"
    owner: "{{ firefox_chown }}"
    group: "{{ firefox_chown }}"
    extra_opts: ["--strip-components", "1"]

# Aparentemente o owner e group acima não fixam as permissões em todos os diretórios.
- name: corrige permissões
  file:
    path: "{{ firefox_path }}"
    recurse: yes
    owner: "{{ firefox_chown }}"
    group: "{{ firefox_chown }}"

- name: remove pacote de download
  file:
    state: absent
    path: "/tmp/firefox-{{ firefox_lang }}-{{ firefox_version }}.tar.bz2"
