---
- name: checa versão instalada
  shell:
    warn=no
    /usr/local/node/bin/node --version | sed -e 's/^v//'
  register: node_register_version
  changed_when: False
  check_mode: no
  failed_when: False
  tags: node

- name: instala node
  include_tasks: install.yml
  when: node_register_version.stdout != node_version or node_force_install is defined
  tags: node
