---
- name: instala pacotes necessários
  apt:
    name:
      - build-essential

- name: faz download do rust-analyzer
  include_role:
    name: zanardo/download
  vars:
    url: https://github.com/rust-analyzer/rust-analyzer/archive/{{ rust_analyzer_version }}.tar.gz
    file: rust-analyzer-{{ rust_analyzer_version }}.tar.gz
    dir: /tmp

- name: descompacta e compila o pacote
  become: yes
  become_user: _builder
  shell: |
    warn=no
    executable=/bin/bash
    cd ~ && \
    rm -rf rust-analyzer* && \
    tar xf /tmp/rust-analyzer-{{ rust_analyzer_version }}.tar.gz && \
    cd rust-analyzer-{{ rust_analyzer_version }} && \
    source /etc/profile.d/rust.sh && \
    export RUST_ANALYZER_REV="{{ rust_analyzer_version }}" && \
    cargo build --release && \
    cp -f target/release/rust-analyzer /tmp && \
    cd ~ && \
    rm -rf rust-analyzer*

- name: instala o binário
  copy:
    remote_src: yes
    src: /tmp/rust-analyzer
    dest: /usr/local/bin/rust-analyzer
    owner: root
    group: root
    mode: 0o755

- name: remove arquivos temporários
  file:
    state: absent
    path: /tmp/{{ item }}
  loop:
    - rust-analyzer-{{ rust_analyzer_version }}.tar.gz
    - rust-analyzer
