- name: instala rust-analyzer
  include_role:
    name: zanardo/rust-app
  vars:
    rust_app_name: rust-analyzer
    rust_app_version: "{{ rust_analyzer_version }}"
    rust_app_apt_packages:
      - build-essential
    rust_app_cmd_get_version: >
      /usr/local/bin/rust-analyzer --version | cut -f2 -d' '
    rust_app_url: >
      https://github.com/rust-analyzer/rust-analyzer/archive/{{ rust_analyzer_version }}.tar.gz
    rust_app_executables:
      - rust-analyzer
    rust_app_env:
      RUST_ANALYZER_REV: "{{ rust_analyzer_version }}"
  tags: ["rust-analyzer"]
