---
- name: instala pacotes necessários
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - supervisor
  tags: ["supervisor"]

- name: carrega supervisor
  service:
    name: supervisor
    state: started
