---
- block:

  - setup:

  - name: instala pacotes necessários para rodar containers
    apt:
      state: present
      install_recommends: no
      name:
        - debootstrap
        - systemd-container
        - zstd

  - name: cria diretório de configurações dos containers
    file:
      state: directory
      path: /etc/systemd/nspawn

  - name: cria configurações do container
    copy:
      content: "{{ nspawn_container_nspawn_config }}"
      dest: "/etc/systemd/nspawn/{{ nspawn_container_name }}.nspawn"
    register: conf

  - name: recarrega configurações systemd
    command:
      systemctl daemon-reload
    when: conf is changed

  - name: cria volume lvm do container
    lvol:
      lv: "{{ nspawn_container_name }}"
      size: "{{ nspawn_container_lvm_lv_size }}"
      state: present
      vg: "{{ nspawn_container_lvm_vg }}"
      resizefs: yes

  - name: "formata o volume lvm do container"
    filesystem:
      dev: "/dev/{{ nspawn_container_lvm_vg }}/{{ nspawn_container_name }}"
      fstype: "ext4"

  - name: "configura montagem do volume em fstab"
    mount:
      fstype: "ext4"
      src: "/dev/{{ nspawn_container_lvm_vg }}/{{ nspawn_container_name }}"
      path: "{{ nspawn_container_dir }}"
      state: mounted
      opts: "nofail"

  - name: cria container a partir de imagem pré-definida
    unarchive:
      src: "{{ nspawn_container_image }}"
      creates: "{{ nspawn_container_dir }}/etc/.stage1.ok"
      dest: "{{ nspawn_container_dir }}"
      remote_src: yes

  - name: cria lock da imagem descompactada
    copy:
      dest: "{{ nspawn_container_dir }}/etc/.stage1.ok"
      content: ""

  - name: verifica se é necessário bootstrap
    stat:
      path: "{{ nspawn_container_dir }}/etc/.stage2.ok"
    register: st

  delegate_to: "{{ nspawn_container_host }}"

- name: executa tasks de bootstrap
  include_tasks: bootstrap.yml
  when: not st.stat.exists

- name: configura inicialização de container - ativo
  command:
    warn=no
    machinectl enable {{ nspawn_container_name }}
  delegate_to: "{{ nspawn_container_host }}"
  changed_when: False
  when: nspawn_container_autostart

- name: configura inicialização de container - desativado
  command:
    warn=no
    machinectl disable {{ nspawn_container_name }}
  changed_when: False
  delegate_to: "{{ nspawn_container_host }}"
  when: not nspawn_container_autostart
