---
- name: instala pacotes - debian
  apt:
    name: shorewall
    state: present
  register: shorewall_install_register
  when: ansible_distribution == "Debian"
  tags: ["shorewall"]

- name: instala pacotes - centos
  yum:
    name: shorewall
    state: present
  register: shorewall_install_register
  when: ansible_distribution == "CentOS"
  tags: ["shorewall"]

- name: habilita serviço do systemd
  shell: systemctl enable shorewall
  when: shorewall_install_register|changed
  tags: ["shorewall"]

- name: habilita início no boot - debian
  lineinfile:
    dest: /etc/default/shorewall
    line: "startup=1"
    regexp: "^startup="
    state: present
  notify: reconfigura shorewall
  when: ansible_distribution == "Debian"
  tags: ["shorewall"]

- name: habilita início no boot - centos
  lineinfile:
    dest: /etc/shorewall/shorewall.conf
    regexp: "^STARTUP_ENABLED="
    line: "STARTUP_ENABLED=Yes"
    state: present
  notify: reconfigura shorewall
  when: ansible_distribution == "CentOS"
  tags: ["shorewall"]

- name: verifica se a reconfiguração falhou
  file:
    path: /tmp/ansible-shorewall-restart
    state: absent
  notify: reconfigura shorewall
  tags: ["shorewall", "shorewall:conf"]

- name: copia arquivos de configuração
  template:
    src: "{{ item }}"
    dest: "/etc/shorewall/{{ item|basename() }}"
    owner: root
    mode: 0600
  with_fileglob:
    - "{{ shorewall_conf }}"
  notify: reconfigura shorewall
  tags: ["shorewall", "shorewall:conf"]
