---
- block:

  - include_tasks: "{{ ansible_distribution|lower }}.yml"

  - name: verifica se a reconfiguração falhou
    file:
      path: /tmp/ansible-shorewall-restart
      state: absent
    notify: reconfigura shorewall
    tags: ["shorewall:conf"]

  - name: copia arquivos de configuração
    template:
      src: "{{ item }}"
      dest: "/etc/shorewall/{{ item|basename() }}"
      owner: root
      mode: 0600
    with_fileglob:
      - "{{ shorewall_conf }}"
    notify: reconfigura shorewall
    tags: ["shorewall:conf"]

  tags: ["shorewall"]
