---
- name: executa tasks específicas de uma distribuição
  include_tasks: setup-{{ ansible_distribution|lower }}.yml

- name: verifica se a reconfiguração falhou
  file:
    path: /tmp/ansible-shorewall-restart
    state: absent
  notify: reconfigura shorewall
  tags:
    - shorewall
    - shorewall:conf

- name: copia arquivos de configuração
  template:
    src: "{{ item }}"
    dest: "/etc/shorewall/{{ item|basename() }}"
    owner: root
    mode: 0600
  with_fileglob:
    - "{{ shorewall_conf }}"
  notify: reconfigura shorewall
  tags:
    - shorewall
    - shorewall:conf
