---
- name: instala pacotes necessários
  apt:
    name:
      - build-essential
      - pkg-config
      - libssl-dev
      - cmake
      - libxdo3
      - libxdo-dev
      - libxtst6
      - libxtst-dev
      - xclip
      - libnotify-bin

- name: faz download do espanso
  include_role:
    name: zanardo/download
  vars:
    url: https://github.com/federico-terzi/espanso/archive/v{{ espanso_version }}.tar.gz
    file: espanso-{{ espanso_version }}.tar.gz
    dir: /tmp

- name: descompacta e compila o pacote
  become: yes
  become_user: _builder
  shell: |
    warn=no
    executable=/bin/bash
    cd ~ && \
    rm -rf espanso* && \
    tar xf /tmp/espanso-{{ espanso_version }}.tar.gz && \
    cd espanso-{{ espanso_version }} && \
    source /etc/profile.d/rust.sh && \
    cargo build --release && \
    cp -f target/release/espanso /tmp && \
    cd ~ && \
    rm -rf espanso*

- name: instala o binário
  copy:
    remote_src: yes
    src: /tmp/espanso
    dest: /usr/local/bin/espanso
    owner: root
    group: root
    mode: 0o755

- name: remove arquivos temporários
  file:
    state: absent
    path: /tmp/{{ item }}
  loop:
    - espanso-{{ espanso_version }}.tar.gz
    - espanso
