---
- name: instala espanso
  include_role:
    name: zanardo/rust-app
    apply:
      tags: ["espanso"]
  vars:
    rust_app_name: espanso
    rust_app_version: "{{ espanso_version }}"
    rust_app_apt_packages:
      - build-essential
      - pkg-config
      - libssl-dev
      - cmake
      - libxdo3
      - libxdo-dev
      - libxtst6
      - libxtst-dev
      - xclip
      - libnotify-bin
    rust_app_cmd_get_version: >
      /usr/local/bin/espanso --version | cut -f2 -d' '
    rust_app_url: >
      https://github.com/federico-terzi/espanso/archive/v{{ espanso_version }}.tar.gz
    rust_app_executables:
      - espanso
  tags: ["espanso"]
