---
- block:
  - name: verifica versão instalada
    shell: |
      warn=no
      dpkg -s dbeaver-ce | grep Version | cut -f2 -d: | sed -e 's/ *//'
    changed_when: False
    failed_when: False
    check_mode: no
    register: version

  - name: faz download do dbeaver
    include_role:
      name: zanardo/download
    vars:
      url: "https://github.com/dbeaver/dbeaver/releases/download/{{ dbeaver_version }}/dbeaver-ce_{{ dbeaver_version }}_amd64.deb"
      file: "dbeaver-ce_{{ dbeaver_version }}_amd64.deb"
      dir: "/tmp"

  - name: instala dbeaver
    apt:
      deb: "/tmp/dbeaver-ce_{{ dbeaver_version }}_amd64.deb"
    when: version.stdout != dbeaver_version

  tags: ["dbeaver"]
