---
- block:

  - name: instala pacotes necessários
    apt:
      name:
        - squid3

  - name: copia arquivo de configurações customizado
    template:
      src: "{{ squid_conf }}"
      dest: /etc/squid/squid.conf
    when: squid_conf|d()
    notify: reconfigura squid
    tags: ["squid:conf"]

  tags: ["squid"]
