---
- block:
    - name: faz download do go
      include_role:
        name: zanardo/download
      vars:
        url: "https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz"
        file: "go{{ go_version }}.linux-amd64.tar.gz"
        dir: "/tmp"

    - name: remove instalação anterior
      file:
        state: absent
        path: /usr/local/go

    - name: extrai o tarball
      shell: >
        warn=no
        chdir="/tmp"
        mkdir /usr/local/go &&
        tar -C /usr/local/go --strip-components=1 \
          --owner root --group root \
          -xzf "/tmp/go{{ go_version }}.linux-amd64.tar.gz"

  tags: ["go"]
