---
- block:
    - name: instala pacotes necessários
      apt:
        name:
          - ca-certificates
        state: present

    - name: download do tarball
      get_url:
        url: "https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz"
        dest: "/tmp/go-{{ go_version }}.tar.gz"

    - name: remove instalação anterior
      file:
        state: absent
        path: /usr/local/go

    - name: extrai o tarball
      shell: >
        warn=no
        chdir="/tmp"
        mkdir /usr/local/go &&
        tar -C /usr/local/go --strip-components=1 \
          --owner root --group root \
          -xzf "/tmp/go{{ go_version }}.linux-amd64.tar.gz"

  tags: ["go"]
