---
- block:

  - name: remove configurações antigas de proxy
    file:
      name: "/etc/apt/apt.conf.d/{{ item }}"
      state: absent
    with_items:
        - 01proxy
        - 01proxy_nohttps

  - block:

    - name: verifica se proxy apt está ativo
      wait_for:
        host: "{{ apt_proxy_host }}"
        port: "{{ apt_proxy_port }}"
        timeout: 5
      when: apt_proxy_host|d
      register: apt_proxy_active

    rescue:

    - name: proxy inativo
      debug:
        msg: "apt_proxy_host:apt_proxy_port não alcançável"

  - name: ativa proxy para apt
    lineinfile:
      path: /etc/apt/apt.conf
      line: "Acquire::http::Proxy \"http://{{ apt_proxy_host }}:{{ apt_proxy_port }}/\";"
      regexp: "^Acquire::http::Proxy "
      state: present
      create: yes
    when: apt_proxy_host|d and apt_proxy_active|succeeded
    register: apt_proxy_set

  - name: desativa proxy para apt
    lineinfile:
      path: /etc/apt/apt.conf
      regexp: "^Acquire::http::Proxy "
      state: absent
    when: apt_proxy_set|skipped

  - name: desativa proxy para repositórios https para apt
    lineinfile:
      path: /etc/apt/apt.conf
      line: "Acquire::https::Proxy \"DIRECT\";"
      regexp: "^Acquire::https::Proxy "
      state: present
    when: apt_proxy_no_https is defined

  - name: ativa proxy para repositórios https para apt
    lineinfile:
      path: /etc/apt/apt.conf
      regexp: "^Acquire::https::Proxy "
      state: absent
    when: apt_proxy_no_https is not defined

  tags: apt-proxy
