---
- name: instala mypy
  include_role:
    name: zanardo/python-app
    apply:
      tags: ["mypy"]
  vars:
    python_app_name: mypy
    python_app_version: "{{ mypy_version }}"
    python_app_scripts:
      - mypy
      - dmypy
      - mypyc
      - stubgen
      - stubtest
  tags: ["mypy"]
