---
- name: instala pacotes necessários
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - ca-certificates
    - libssl-dev
    - luajit
    - libluajit-5.1-dev

- name: cria diretório /usr/local/src
  file: >
    state=directory
    dest="/usr/local/src"

- name: download do tarball
  get_url: >
    url="https://github.com/wg/wrk/archive/{{ wrk_version }}.tar.gz"
    dest="/usr/local/src/wrk-{{ wrk_version }}.tar.gz"

- name: descompacta tarball
  shell: >
    warn=no
    chdir=/tmp
    tar xzf "/usr/local/src/wrk-{{ wrk_version }}.tar.gz"

- name: corrige permissões do source
  shell: >
    warn=no
    chown -R nobody:nogroup "/tmp/wrk-{{ wrk_version }}"

- name: compila
  become: yes
  become_user: nobody
  shell: >
    chdir="/tmp/wrk-{{ wrk_version }}/"
    make WITH_LUAJIT=/usr WITH_OPENSSL=/usr

- name: instala
  shell: >
    chdir="/tmp/wrk-{{ wrk_version }}/"
    install -o root -g root -m 0755 wrk /usr/local/bin/wrk
  notify: reinicia wrk

- name: remove arquivos temporários
  become: yes
  become_user: nobody
  file: >
    state=absent
    path="/tmp/wrk-{{ wrk_version }}"
