---
- name: verifica se variável 'wrk_version' está definida
  assert: that="wrk_version is defined"

- name: checa se wrk está instalado, e qual versão
  shell: "/usr/local/bin/wrk --version | head -n1 | cut -f3 -d' '"
  register: wrk_register_version
  changed_when: False
  failed_when: False

- name: download do código-fonte, compila e instala
  include: install.yml
  when: wrk_register_version.stdout != wrk_version or wrk_force_install is defined
