---
- block:
    - name: instala pacotes necessários
      apt:
        name:
          - redis-server
        state: present

    - name: copia arquivo de configuração
      template:
        src: "{{ redis_conf }}"
        dest: /etc/redis/redis.conf
      when: redis_conf is defined
      tags: ["redis:conf"]

  tags: ["redis"]
