---
- name: define configurações do sysctl
  sysctl:
    sysctl_file: /etc/sysctl.d/local.conf
    state: present
    name: '{{ item }}'
    value: '{{ sysctl_set[item] }}'
    ignoreerrors: yes
  with_items: '{{ sysctl_set }}'
  tags: sysctl
