---
- name: instala pacotes necessários
  apt: name="{{ item }}" state=present
  with_items:
    - gtk2-engines-murrine
    - git

- block:
  # become, become_user

  - name: cria diretório ~/.themes
    file: >
      state=directory
      path="~/.themes"

  - name: clona repositório do tema
    git: >
      dest="~/.themes/Greybird"
      repo="https://github.com/shimmerproject/Greybird"
      update=no
      version="gtk3.14-spinner"

  become: yes
  become_user: "{{ gtk_theme_greybird_user }}"
