---
- name: instala pacotes necessários
  apt:
    name: haproxy
    state: present
  tags: ["haproxy"]

- name: copia arquivo de configuração
  template:
    src: "{{ haproxy_conf }}"
    dest: /etc/haproxy/haproxy.cfg
  when: haproxy_conf is defined
  notify: recarrega haproxy
  tags: ["haproxy", "haproxy:conf"]
