#!/bin/bash

set -exuo pipefail

VERSION="${1}"
test -n "${VERSION}"
test -n "${ARTIFACTS}"

rm -f "/tmp/winbox_${VERSION}.exe"

if [ ! -f "/tmp/winbox_${VERSION}.exe" ]; then
    wget -O "/tmp/winbox_${VERSION}.exe.tmp" \
        "https://download.mikrotik.com/winbox/${VERSION}/winbox.exe"
    mv -f "/tmp/winbox_${VERSION}.exe.tmp" \
        "/tmp/winbox_${VERSION}.exe"
fi

rsync -vax --ignore-existing \
    "/tmp/winbox_${VERSION}.exe" \
    "${ARTIFACTS}/winbox/"
