---
- name: instala ipython
  include_role:
    name: zanardo/python-app
    apply:
      tags: ["ipython"]
  vars:
    python_app_name: ipython
    python_app_version: "{{ ipython_version }}"
    python_app_scripts:
      - ipython
  tags: ["ipython"]
