---
- block:

  - name: cria diretórios para os pacotes
    file:
      state: directory
      path: /opt/ipython
      owner: nobody
      group: nogroup

  - name: instala os pacotes
    become: yes
    become_user: nobody
    pip:
      name: ipython
      version: "{{ ipython_version|d(omit) }}"
      virtualenv_python: /usr/bin/python3
      virtualenv: /opt/ipython

  - name: cria symlinks para os scripts
    file:
      state: link
      src: /opt/ipython/bin/{{ item }}
      dest: /usr/local/bin/{{ item }}
    loop:
      - ipython

  tags: ["ipython"]
