---
- block:

    - name: copia sources.list
      template:
        src: "{{ sources_list_path|d(ansible_distribution_release + '.list') }}"
        dest: /etc/apt/sources.list
      when: ansible_distribution in ("Debian", "Ubuntu")
      register: sources_list_register

    - name: recarrega repositórios
      apt:
        update_cache: yes
      when: sources_list_register is changed

  tags: ["apt-sources"]
