---
- block:
    - name: permite atualizações de repositórios arquivados
      copy:
        content: 'Acquire::Check-Valid-Until "0";'
        dest: /etc/apt/apt.conf.d/99old-repos
      when: ansible_distribution_release in ("wheezy", "jessie")

    - name: copia sources.list do debian
      template:
        src: "{{ sources_list_path|d(ansible_distribution_release + '.list') }}"
        dest: /etc/apt/sources.list
      when: ansible_distribution == "Debian"
      register: sources_list_register

    - name: recarrega repositórios debian
      apt:
        update_cache: yes
      when: sources_list_register is changed

  tags: sources_list
