---
- block:

    - name: instala pacotes necessários
      apt:
        state: present
        name: chrony

    - name: copia arquivo de configuração
      template:
        src: "{{ chrony_conf|d('chrony.conf') }}"
        dest: /etc/chrony/chrony.conf
        mode: 0644
        owner: root
        group: root
      notify: reinicia chrony
      tags: ["chrony:conf"]

    - name: habilita e carrega chrony no systemd
      systemd:
        name: chrony
        enabled: yes
        state: started

  tags: ["chrony"]
