---
- block:

  - name: instala pacotes necessários
    apt:
      state: present
      name: chrony

  - name: copia arquivo de configuração default do role
    copy:
      src: chrony.conf
      dest: /etc/chrony/chrony.conf
      mode: 0755
      owner: root
      group: root
    notify: reinicia chrony
    when: chrony_conf is not defined
    tags: ["chrony:conf"]

  - name: copia arquivo de configuração customizado
    template:
      src: "{{ chrony_conf }}"
      dest: /etc/chrony/chrony.conf
      mode: 0755
      owner: root
      group: root
    notify: reinicia chrony
    when: chrony_conf is defined
    tags: ["chrony:conf"]

  - name: habilita chrony no systemd
    systemd:
      name: chrony
      enabled: yes
      state: started

  tags: chrony
