---
- name: download do tarball
  get_url:
    dest: "/tmp/firefox-{{ firefox_version }}-{{ firefox_lang }}.tar.bz2"
    url: "http://ftp.mozilla.org/pub/firefox/releases/{{ firefox_version }}/linux-{{ ansible_architecture }}/{{ firefox_lang }}/firefox-{{ firefox_version }}.tar.bz2"

- name: copia chave de assinatura do gpg
  copy:
    dest: /tmp/mozilla_firefox.key
    src: mozilla_firefox.key

- name: importa chave pública do gpg no keyring
  shell: >
    chdir=/tmp
    gpg --no-default-keyring --homedir=. --import /tmp/mozilla_firefox.key

- name: download dos arquivos com sha512sum
  get_url:
    url: "http://ftp.mozilla.org/pub/firefox/releases/{{ firefox_version }}/{{ item }}"
    dest: "/tmp/mozilla_{{ item }}"
    force: yes
  with_items: ["SHA512SUMS", "SHA512SUMS.asc"]

- name: verifica assinatura do arquivo SHA512SUMS via gpg
  shell: >
    chdir=/tmp
    gpg --no-default-keyring --homedir=. --verify mozilla_SHA512SUMS.asc mozilla_SHA512SUMS

- name: verifica sha512sum do tarball
  shell: >
    chdir=/tmp
    shadw=$(sha512sum "firefox-{{ firefox_version }}-{{ firefox_lang }}.tar.bz2" | cut -d" " -f1) ; \
    grep "$shadw" /tmp/mozilla_SHA512SUMS

- name: remove instalação anterior
  file:
    state: absent
    path: "/opt/firefox"

- name: cria diretórios necessários
  file:
    state: directory
    path: "/opt/firefox"
    mode: 0755

- name: extrai tarball
  shell: >
    warn=no
    tar -C /opt/firefox --strip-components=1 -xjf \
      "/tmp/firefox-{{ firefox_version }}-{{ firefox_lang }}.tar.bz2"

- name: cria symlink para /usr/local/bin/firefox
  file:
    path: "/usr/local/bin/firefox"
    src: "/opt/firefox/firefox"
    state: link
