---
- name: download do tarball
  connection: local
  get_url:
    url: "http://ftp.mozilla.org/pub/firefox/releases/{{ firefox_version }}/linux-{{ ansible_architecture }}/{{ firefox_lang }}/firefox-{{ firefox_version }}.tar.bz2"
    dest: "~/.cache/ansible/firefox-{{ firefox_version }}-{{ firefox_lang }}.tar.bz2"

- name: download dos arquivos com sha512sum
  connection: local
  get_url:
    url: "http://ftp.mozilla.org/pub/firefox/releases/{{ firefox_version }}/{{ item }}"
    dest: "~/.cache/ansible/firefox-{{ firefox_version }}.{{ item }}"
  with_items: ["SHA512SUMS", "SHA512SUMS.asc"]

- name: copia chave de assinatura do gpg
  copy:
    src: "mozilla_firefox.key"
    dest: "/tmp/firefox-{{ firefox_version }}.key"

- name: copia downloads
  copy:
    dest: "/tmp/{{ item }}"
    src: "~/.cache/ansible/{{ item }}"
  with_items:
    - "firefox-{{ firefox_version }}-{{ firefox_lang }}.tar.bz2"
    - "firefox-{{ firefox_version }}.SHA512SUMS"
    - "firefox-{{ firefox_version }}.SHA512SUMS.asc"

- name: importa chave pública do gpg no keyring
  shell: >
    chdir=/tmp
    gpg --no-default-keyring --homedir=. --import "/tmp/firefox-{{ firefox_version }}.key"

- name: verifica assinatura do arquivo SHA512SUMS via gpg
  shell: >
    chdir=/tmp
    gpg --no-default-keyring --homedir=. --verify "firefox-{{ firefox_version }}.SHA512SUMS.asc" "firefox-{{ firefox_version }}.SHA512SUMS"

- name: verifica sha512sum do tarball
  shell: >
    chdir=/tmp
    shadw=$(sha512sum "firefox-{{ firefox_version }}-{{ firefox_lang }}.tar.bz2" | cut -d" " -f1) ; \
    grep "$shadw" "firefox-{{ firefox_version }}.SHA512SUMS"

- name: remove instalação anterior
  file:
    state: absent
    path: "/opt/firefox"

- name: cria diretórios necessários
  file:
    state: directory
    path: "/opt/firefox"
    mode: 0755

- name: extrai tarball
  shell: >
    warn=no
    tar -C /opt/firefox --strip-components=1 -xjf \
      "/tmp/firefox-{{ firefox_version }}-{{ firefox_lang }}.tar.bz2"

- name: corrige permissões
  file:
    state: directory
    recurse: yes
    path: /opt/firefox
    owner: root
    group: root

- name: cria symlink para /usr/local/bin/firefox
  file:
    path: "/usr/local/bin/firefox"
    src: "/opt/firefox/firefox"
    state: link

- name: remove arquivos temporários
  file:
    state: absent
    path: "/tmp/{{ item }}"
  with_items:
    - "firefox-{{ firefox_version }}-{{ firefox_lang }}.tar.bz2"
    - "firefox-{{ firefox_version }}.key"
    - "firefox-{{ firefox_version }}.SHA512SUMS"
    - "firefox-{{ firefox_version }}.SHA512SUMS.asc"
