- name: instala tokei
  include_role:
    name: zanardo/rust-app
    apply:
      tags: ["tokei"]
  vars:
    rust_app_name: tokei
    rust_app_version: "{{ tokei_version }}"
    rust_app_apt_packages:
      - build-essential
    rust_app_cmd_get_version: >
      /usr/local/bin/tokei --version | cut -f2 -d' '
    rust_app_url: >
      https://github.com/XAMPPRocky/tokei/archive/v{{ tokei_version }}.tar.gz
    rust_app_executables:
      - tokei
  tags: ["tokei"]
