---
- block:

    - name: instala pacotes necessários - python2
      apt:
        name:
          - python
          - python-dev
          - python-pip
      when:
        - python_install_python2
        - ansible_distribution_release not in ("bullseye")

    - name: instala pacotes necessários - python3
      apt:
        name:
          - python3
          - python3-dev
          - python3-pip
          - python3-venv
      when: python_install_python3

    - name: instala virtualenv atualizado /usr/local
      shell: warn=no
        creates=/usr/local/bin/virtualenv
        pip3 install --upgrade virtualenv
      when: python_install_virtualenv

  tags: ["python"]
