---
- block:

  - name: instala pacote lvm2
    apt:
      name: lvm2
      state: present
    when: 'storage_lvm_lvs|d or storage_lvm_vgs|d'

  - name: configura volume groups do lvm
    lvg:
      vg: '{{ item.name }}'
      pvs: '{{ item.pvs }}'
    with_items: '{{ storage_lvm_vgs|d([]) }}'

  - name: configura logical volumes do lvm
    lvol:
      lv: '{{ item.name }}'
      vg: '{{ item.vg }}'
      size: '{{ item.size }}'
    with_items: '{{ storage_lvm_lvs|d([]) }}'

  - name: cria filesystems
    filesystem:
      dev: '{{ item.dev }}'
      fstype: '{{ item.fstype }}'
    with_items: '{{ storage_fs|d([]) }}'

  - name: configura montagem em /etc/fstab
    mount:
      fstype: '{{ item.fstype }}'
      dump: '{{ item.dump|d("0") }}'
      name: '{{ item.name }}'
      opts: '{{ item.opts|d("defaults") }}'
      passno: '{{ item.passno|d("0") }}'
      src: '{{ item.src }}'
      state: '{{ item.state|d("present") }}'
    with_items: '{{ storage_mount|d([]) }}'

  - name: configura owner dos diretórios raiz montados
    file:
      state: directory
      owner: '{{ item.owner }}'
      path: '{{ item.name }}'
    when: item.state == 'mounted' and item.owner|d(False)
    with_items: '{{ storage_mount|d([]) }}'

  tags: storage
