---
- name: instala os cabeçalhos de compilação para kernel
  apt:
    name: "linux-headers-{{ ansible_kernel }}"
    state: present
  tags: zfs

- name: instala pacotes do zfs (dkms)
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  loop:
    - zfsutils-linux
    - zfs-dkms
  tags: zfs

- name: carrega o módulo do kernel
  modprobe:
    name: zfs
    state: present
  tags: zfs
