---
- block:

  - name: instala os pacotes necessários para compilação
    apt:
      name:
        - build-essential
        - linux-headers-amd64
        - "linux-headers-{{ ansible_kernel }}"
      state: present

  # O pacote zfsutils-linux falha ao instalar no Buster sem carregar o módulo zfs.
  - name: instala módulo do zfs
    apt:
      name:
        - zfs-dkms
      state: present
      install_recommends: no

  - name: configura o módulo do zfs
    copy:
      dest: "/etc/modprobe.d/zfs.conf"
      content: |
        {% for item in zfs_mod_conf %}
        options zfs {{ item }}={{ zfs_mod_conf[item] }}
        {% endfor %}
    tags: ["zfs:conf"]

  - name: carrega o módulo do kernel
    modprobe:
      name: zfs
      state: present

  - name: instala ferramentas do zfs
    apt:
      name:
        - zfsutils-linux
      state: present
      install_recommends: no

  tags: ["zfs"]
