---
- name: instala pacotes necessários
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - redis-server
  tags: ["redis"]

- name: copia arquivo de configuração
  template:
    src: "{{ redis_conf }}"
    dest: /etc/redis/redis.conf
  when: redis_conf|d
  tags: ["redis", "redis:conf"]
