---
- name: verifica se variável 'redis_version' está definida
  assert: that="redis_version is defined"

- name: checa se redis está instalado, e qual versão
  shell: "/usr/local/bin/redis-server --version | cut -f3 -d' ' | cut -f2 -d="
  register: redis_register_version
  changed_when: False
  failed_when: False

- name: download do código-fonte, compila e instala
  include: install.yml
  when: redis_register_version.stdout != redis_version or redis_force_install is defined

- name: prepara a instância
  include: instance.yml
