---
- name: instala pacotes necessários
  apt:
    name:
      - build-essential

- name: faz download do hyperfine
  include_role:
    name: zanardo/download
  vars:
    url: https://github.com/sharkdp/hyperfine/archive/v{{ hyperfine_version }}.tar.gz
    file: hyperfine-{{ hyperfine_version }}.tar.gz
    dir: /tmp

- name: descompacta e compila o pacote
  become: yes
  become_user: _builder
  shell: |
    warn=no
    executable=/bin/bash
    cd ~ && \
    rm -rf hyperfine* && \
    tar xf /tmp/hyperfine-{{ hyperfine_version }}.tar.gz && \
    cd hyperfine-{{ hyperfine_version }} && \
    source /etc/profile.d/rust.sh && \
    cargo build --release && \
    cp -f target/release/hyperfine /tmp && \
    cd ~ && \
    rm -rf hyperfine*

- name: instala o binário
  copy:
    remote_src: yes
    src: /tmp/hyperfine
    dest: /usr/local/bin/hyperfine
    owner: root
    group: root
    mode: 0o755

- name: remove arquivos temporários
  file:
    state: absent
    path: /tmp/{{ item }}
  loop:
    - hyperfine-{{ hyperfine_version }}.tar.gz
    - hyperfine
