---
- name: instala hyperfine
  include_role:
    name: zanardo/rust-app
    apply:
      tags: ["hyperfine"]
  vars:
    rust_app_name: hyperfine
    rust_app_version: "{{ hyperfine_version }}"
    rust_app_apt_packages:
      - build-essential
    rust_app_cmd_get_version: >
      /usr/local/bin/hyperfine --version | cut -f2 -d' '
    rust_app_url: >
      https://github.com/sharkdp/hyperfine/archive/refs/tags/v{{ hyperfine_version }}.tar.gz
    rust_app_executables:
      - hyperfine
  tags: ["hyperfine"]
