---
- block:
  - name: configura proxy para apt
    copy:
      dest: /etc/apt/apt.conf.d/01proxy
      content: "Acquire::http::Proxy \"{{ apt_proxy }}\";"
      owner: root
      group: root
      mode: 0644
    when: apt_proxy is defined

  - name: desativa proxy para repositórios https para apt
    copy:
      dest: /etc/apt/apt.conf.d/01proxy_nohttps
      content: "Acquire::https::Proxy \"false\";"
      owner: root
      group: root
      mode: 0644
    when: apt_proxy_no_https is defined

  - name: configura apt sources.list
    copy:
      src: sources.list
      dest: /etc/apt/sources.list
      owner: root
      group: root
      mode: 0644
    notify: atualiza apt

  - name: desativa dns para ssh
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      line: "UseDNS no"
      regexp: "^UseDNS .*$"
    notify: reinicia ssh

  - meta: flush_handlers

  - name: reduz tempo de espera no menu do grub
    lineinfile:
      dest: /etc/default/grub
      line: "GRUB_TIMEOUT=1"
      regexp: "^#?GRUB_TIMEOUT="
      state: present
    notify: reconfigura grub

  - name: instala pacotes básicos
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-dater-host

  tags: common
