---
- name: instala pacotes necessários
  apt:
    name:
      - ca-certificates
    state: present

- name: faz download do tarball para cache loca
  connection: local
  run_once: yes
  get_url:
    url: "https://github.com/zanardo/rrd-collectors/archive/v{{ rrd_collectors_version }}.tar.gz"
    dest: "~/.cache/ansible/rrd-collectors-{{ rrd_collectors_version }}.tar.gz"

- name: faz upload do tarball
  copy:
    src: "~/.cache/ansible/rrd-collectors-{{ rrd_collectors_version }}.tar.gz"
    dest: "/tmp/rrd-collectors-{{ rrd_collectors_version }}.tar.gz"

- name: cria diretório de instalação
  file:
    state: directory
    owner: root
    group: root
    path: "/opt/rrd-collectors-{{ rrd_collectors_version }}"

- name: descompacta tarball
  shell: >
    warn=no
    chdir="/opt/rrd-collectors-{{ rrd_collectors_version }}"
    tar --strip-components=1 -C . -xzf "/tmp/rrd-collectors-{{ rrd_collectors_version }}.tar.gz"

- name: corrige permissões para root
  file:
    state: directory
    owner: root
    group: root
    recurse: yes
    path: "/opt/rrd-collectors-{{ rrd_collectors_version }}"

- name: remove arquivos temporários
  file:
    state: absent
    path: "/tmp/rrd-collectors-{{ rrd_collectors_version }}.tar.gz"
