---
- block:
    - name: adiciona arquitetura i386 para dpkg
      lineinfile:
        state: present
        dest: /var/lib/dpkg/arch
        line: i386
        regexp: "^i386$"
        create: yes
      register: dpkg_arch_reg

    - name: recarrega repositórios apt
      apt:
        update_cache: yes
      when: dpkg_arch_reg is changed

    - name: instala pacotes necessários
      apt:
        name:
          - wine
          - wine32

  tags: ["wine"]
