---
- name: instala poetry
  include_role:
    name: zanardo/python-app
    apply:
      tags: ["poetry"]
  vars:
    python_app_name: poetry
    python_app_version: "{{ poetry_version }}"
    python_app_scripts:
      - poetry
  tags: ["poetry"]
