---
- block:

  - name: cria diretórios para os pacotes
    file:
      state: directory
      path: /opt/poetry
      owner: nobody
      group: nogroup

  - name: instala os pacotes
    become: yes
    become_user: nobody
    pip:
      name: poetry
      version: "{{ poetry_version|d(omit) }}"
      virtualenv_python: /usr/bin/python3
      virtualenv: /opt/poetry

  - name: cria symlinks para os scripts
    file:
      state: link
      src: /opt/poetry/bin/{{ item }}
      dest: /usr/local/bin/{{ item }}
    loop:
      - poetry

  tags: ["poetry"]
